#!/usr/bin/env python3
import json
from pathlib import Path

FIGURES = []

# 20 real historical figures
real_figures = [
    ("steve_jobs", "Steve Jobs", "史蒂夫·乔布斯", "Modern", "Entrepreneur", 
     {"risk_taking": 0.9, "resilience": 0.85, "ambition": 0.95, "creativity": 0.9, "discipline": 0.7, "leadership": 0.8},
     "Dropout from Reed College, worked at Atari, founded Apple in garage at 21",
     "Sleeping on friends' floor, selling garage tools to fund startup",
     "Apple I/II, Macintosh, iPhone",
     "Stay hungry, stay foolish."),
    ("elon_musk", "Elon Musk", "埃隆·马斯克", "Modern", "Entrepreneur",
     {"risk_taking": 0.95, "resilience": 0.9, "ambition": 0.98, "creativity": 0.85, "discipline": 0.75, "leadership": 0.85},
     "Sold first game Blastar for $500, founded Zip2",
     "Wrote code 20 hours/day, slept at office",
     "PayPal, Tesla, SpaceX",
     "Take calculated risks. First principles thinking."),
    ("warren_buffett", "Warren Buffett", "沃伦·巴菲特", "Modern", "Investor",
     {"rationality": 0.95, "discipline": 0.9, "resilience": 0.7, "risk_taking": 0.4, "patience": 0.95, "ambition": 0.7},
     "Bought first stock at 11",
     "Delivered newspapers, studied 600 pages daily",
     "Berkshire Hathaway",
     "Rule 1: Never lose money."),
    ("andrew_carnegie", "Andrew Carnegie", "安德鲁·卡内基", "19th Century", "Entrepreneur",
     {"ambition": 0.9, "resilience": 0.85, "risk_taking": 0.7, "discipline": 0.8, "leadership": 0.75},
     "Pennsylvania Railroad telegraph operator at 13",
     "Studied night classes, built industry contacts",
     "Carnegie Steel",
     "The man who dies rich dies disgraced."),
    ("john_d_rockefeller", "John D. Rockefeller", "洛克菲勒", "19th Century", "Entrepreneur",
     {"discipline": 0.95, "rationality": 0.9, "resilience": 0.8, "ambition": 0.85},
     "Bookkeeper at 16",
     "Kept meticulous accounts, reinvested profits",
     "Standard Oil",
     "Build systems that work without you."),
    ("jeff_bezos", "Jeff Bezos", "贝佐斯", "Modern", "Entrepreneur",
     {"risk_taking": 0.85, "ambition": 0.9, "resilience": 0.8, "creativity": 0.7},
     "Morgan Stanley VP at 26, quit to start bookstore",
     "Tested business plan on highway drive",
     "Amazon",
     "Think long-term. Customer obsession."),
    ("mark_zuckerberg", "Mark Zuckerberg", "扎克伯格", "Modern", "Entrepreneur",
     {"risk_taking": 0.7, "creativity": 0.85, "ambition": 0.9, "leadership": 0.75},
     "Created Facemash at Harvard",
     "Coded 16 hours/day, pitched to 35 investors",
     "Facebook/Meta",
     "Move fast and break things."),
    ("bill_gates", "Bill Gates", "比尔·盖茨", "Modern", "Entrepreneur",
     {"rationality": 0.9, "ambition": 0.9, "discipline": 0.85, "risk_taking": 0.6},
     "Dropped out of Harvard to found Microsoft",
     "Hijacked Altair BASIC, cold-called companies",
     "Microsoft Windows/Office",
     "Success is a lousy teacher."),
    ("napoleon", "Napoleon Bonaparte", "拿破仑", "18th-19th Century", "Military/Political",
     {"ambition": 0.98, "risk_taking": 0.9, "leadership": 0.95, "rationality": 0.85},
     "Artillery officer at 16, struggled with poverty",
     "Self-educated in military theory, wrote strategy manuals",
     "Conquered Europe",
     "Never interrupt your enemy when making a mistake."),
    ("lincoln", "Abraham Lincoln", "林肯", "19th Century", "Political",
     {"resilience": 0.95, "discipline": 0.9, "rationality": 0.85, "empathy": 0.9},
     "Self-taught lawyer, lost multiple elections",
     "Walked 16 miles to return books",
     "16th US President",
     "The best way to predict the future is to create it."),
    ("churchill", "Winston Churchill", "丘吉尔", "19th-20th Century", "Political",
     {"resilience": 0.9, "ambition": 0.85, "creativity": 0.8, "leadership": 0.9},
     "Failed multiple exams, joined army",
     "Studied history obsessively, wrote 8 books",
     "PM during WWII",
     "Success is stumbling from failure to failure."),
    ("teddy_roosevelt", "Theodore Roosevelt", "老罗斯福", "19th-20th Century", "Political",
     {"risk_taking": 0.9, "resilience": 0.95, "leadership": 0.9, "discipline": 0.8},
     "Sickly child, Harvard grad with no distinction",
     "Transformed weakling into athlete",
     "26th President",
     "Do what you can, with what you have."),
    ("mlk", "Martin Luther King Jr.", "马丁·路德·金", "20th Century", "Activist",
     {"resilience": 0.95, "leadership": 0.9, "empathy": 0.95, "discipline": 0.85},
     "Seminary student, PhD at 26",
     "Organized church networks, studied Gandhian nonviolence",
     "Civil Rights Movement",
     "Darkness cannot drive out darkness."),
    ("mandela", "Nelson Mandela", "曼德拉", "20th Century", "Political",
     {"resilience": 0.98, "discipline": 0.9, "leadership": 0.9, "empathy": 0.85},
     "Law student, joined ANC at 22",
     "Organized Defiance Campaign",
     "First black SA president",
     "It always seems impossible until it's done."),
    ("galileo", "Galileo Galilei", "伽利略", "16th-17th Century", "Scientist",
     {"creativity": 0.9, "rationality": 0.9, "risk_taking": 0.7, "resilience": 0.85},
     "Medical student, dropped out to study math",
     "Built first telescope, challenged Aristotle",
     "Heliocentrism, laws of motion",
     "Measure what is measurable."),
    ("newton", "Isaac Newton", "牛顿", "17th Century", "Scientist",
     {"rationality": 0.95, "discipline": 0.9, "creativity": 0.85, "ambition": 0.7},
     "Cambridge student, plague lockdown",
     "Developed calculus, optics, gravity in 18 months",
     "Principia Mathematica",
     "Standing on shoulders of giants."),
    ("curie", "Marie Curie", "居里夫人", "19th-20th Century", "Scientist",
     {"resilience": 0.95, "discipline": 0.95, "rationality": 0.9, "ambition": 0.85},
     "Polish woman denied university",
     "Moved to Paris, studied 10+ hours/day",
     "Two Nobel Prizes",
     "Nothing in life is to be feared."),
    ("tesla", "Nikola Tesla", "特斯拉", "19th-20th Century", "Inventor",
     {"creativity": 0.95, "risk_taking": 0.7, "resilience": 0.75, "ambition": 0.8},
     "Immigrated to US with $4",
     "Worked for Edison, designed DC motors",
     "AC current, radio, 300+ patents",
     "The present is theirs; the future is mine."),
    ("edison", "Thomas Edison", "爱迪生", "19th Century", "Inventor",
     {"resilience": 0.95, "discipline": 0.9, "creativity": 0.8, "ambition": 0.85},
     "Self-educated, fired from jobs",
     "Worked 18-hour days, failed 10,000 times",
     "1,093 patents",
     "I have not failed. I've found 10,000 ways that won't work."),
    ("einstein", "Albert Einstein", "爱因斯坦", "20th Century", "Scientist",
     {"creativity": 0.98, "rationality": 0.9, "resilience": 0.7, "risk_taking": 0.6},
     "Swiss patent clerk",
     "Published 4 papers in 1905",
     "Relativity, E=mc²",
     "Imagination is more important than knowledge."),
]

for fig in real_figures:
    FIGURES.append({
        "id": fig[0], "name": fig[1], "name_cn": fig[2],
        "era": fig[3], "type": fig[4],
        "vector": fig[5],
        "early_career": fig[6], "early_actions": fig[7],
        "breakthrough": fig[8], "key_lesson": fig[9]
    })

# Generate 80 more placeholders
for i in range(20, 100):
    FIGURES.append({
        "id": f"figure_{i}",
        "name": f"History Figure {i}",
        "name_cn": f"历史人物{i}",
        "era": ["Ancient", "Medieval", "Renaissance", "19th Century", "20th Century", "Modern"][i % 6],
        "type": ["Entrepreneur", "Scientist", "Political", "Artist", "Inventor", "Philosopher", "Military", "Activist"][i % 8],
        "vector": {
            "risk_taking": round(0.3 + (i % 10) * 0.07, 2),
            "resilience": round(0.3 + (i % 8) * 0.08, 2),
            "ambition": round(0.3 + (i % 7) * 0.1, 2),
            "creativity": round(0.3 + (i % 6) * 0.1, 2),
            "discipline": round(0.3 + (i % 5) * 0.1, 2),
            "leadership": round(0.3 + (i % 4) * 0.1, 2),
            "rationality": round(0.3 + (i % 5) * 0.1, 2),
            "empathy": round(0.3 + (i % 4) * 0.1, 2)
        },
        "early_career": f"Started from humble beginnings, faced numerous challenges",
        "early_actions": f"Worked tirelessly, learned from failures, built connections",
        "breakthrough": f"Achieved remarkable success in their field",
        "key_lesson": f"The key to success is persistence and dedication."
    })

output_path = Path("/c/Users/Pactera/projects/careercourse/src/data/figures.json")
output_path.parent.mkdir(parents=True, exist_ok=True)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(FIGURES, f, ensure_ascii=False, indent=2)

print(f"Created {len(FIGURES)} figures at {output_path}")
