"""Generate 100 historical figures with early career data."""
import json
from pathlib import Path

FIGURES = [
    # === ENTREPRENEURS (25) ===
    {"id": "steve_jobs", "name": "Steve Jobs", "name_cn": "史蒂夫·乔布斯", "era": "Modern", "type": "Entrepreneur", "career_stage": "early", "vector": {"risk_taking": 0.9, "resilience": 0.85, "ambition": 0.95, "creativity": 0.9, "discipline": 0.7, "leadership": 0.8},
     "early_career": "Dropout from Reed College, worked at Atari, founded Apple in garage at 21",
     "early_actions": "Sleeping on friends' floor, selling garage tools to fund startup, cold-calling retailers",
     "breakthrough": "Apple I/II, Macintosh, iPhone - revolutionized multiple industries",
     "key_lesson": "Stay hungry, stay foolish. Focus on products that matter."},
    {"id": "elon_musk", "name": "Elon Musk", "name_cn": "埃隆·马斯克", "era": "Modern", "type": "Entrepreneur", "career_stage": "early", "vector": {"risk_taking": 0.95, "resilience": 0.9, "ambition": 0.98, "creativity": 0.85, "discipline": 0.75, "leadership": 0.85},
     "early_career": "Sold first game Blastar for $500, founded Zip2, sold for $307M",
     "early_actions": "Wrote code 20 hours/day, slept at office, took last airline seat home",
     "breakthrough": "PayPal, Tesla, SpaceX - multiple billion-dollar companies",
     "key_lesson": "Take calculated risks. First principles thinking. Work 80-100 hours/week."},
    {"id": "warren_buffett", "name": "Warren Buffett", "name_cn": "沃伦·巴菲特", "era": "Modern", "type": "Investor", "career_stage": "early", "vector": {"rationality": 0.95, "discipline": 0.9, "resilience": 0.7, "risk_taking": 0.4, "patience": 0.95, "ambition": 0.7},
     "early_career": "Bought first stock at 11, read Graham's Intelligent Investor at 19",
     "early_actions": "Delivered newspapers door-to-door, studied 600 pages of value investing daily",
     "breakthrough": "Berkshire Hathaway - 500% annual returns in 1960s",
     "key_lesson": "Rule 1: Never lose money. Rule 2: Never forget rule 1. Compound over time."},
    {"id": "andrew_carnegie", "name": "Andrew Carnegie", "name_cn": "安德鲁·卡内基", "era": "19th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"ambition": 0.9, "resilience": 0.85, "risk_taking": 0.7, "discipline": 0.8, "leadership": 0.75},
     "early_career": "Pennsylvania Railroad telegraph operator at age 13, $1.20/week",
     "early_actions": "Studied night classes, built network of industry contacts, invested in telegraph",
     "breakthrough": "Carnegie Steel - produced more steel than Britain",
     "key_lesson": "The man who dies rich, dies disgraced. Give away wealth."},
    {"id": "john_d Rockefeller", "name": "John D. Rockefeller", "name_cn": "约翰·D·洛克菲勒", "era": "19th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"discipline": 0.95, "rationality": 0.9, "resilience": 0.8, "ambition": 0.85, "risk_taking": 0.5, "leadership": 0.7},
     "early_career": "Bookkeeper at 16, started oil refining at 24 with partner",
     "early_actions": "Kept meticulous accounts, reinvested every profit, studied competitors",
     "breakthrough": "Standard Oil - controlled 90% of US oil refining",
     "key_lesson": "Build systems. Efficiency beats luck. Compound small wins."},
    {"id": "amazon_bezos", "name": "Jeff Bezos", "name_cn": "杰夫·贝佐斯", "era": "Modern", "type": "Entrepreneur", "career_stage": "early", "vector": {"risk_taking": 0.85, "ambition": 0.9, "resilience": 0.8, "creativity": 0.7, "discipline": 0.75, "leadership": 0.85},
     "early_career": "Morgan Stanley VP at 26, quit to start online bookstore",
     "early_actions": "Tested business plan on highway drive to Denver, hired first 5 engineers from contacts",
     "breakthrough": "Amazon - world's largest retailer and cloud provider",
     "key_lesson": "Regret minimization framework. Think long-term. Customer obsession."},
    {"id": "mark Zuckerberg", "name": "Mark Zuckerberg", "name_cn": "马克·扎克伯格", "era": "Modern", "type": "Entrepreneur", "career_stage": "early", "vector": {"risk_taking": 0.7, "creativity": 0.85, "ambition": 0.9, "leadership": 0.75, "discipline": 0.6, "resilience": 0.7},
     "early_career": "Created Facemash at Harvard while dropping out",
     "early_actions": "Coded 16 hours/day in dorm, lived on Ramen, pitched to 35 investors",
     "breakthrough": "Facebook/Meta - 3 billion users, social media revolution",
     "key_lesson": "Move fast and break things. The biggest risk is not taking one."},
    {"id": "bill_gates", "name": "Bill Gates", "name_cn": "比尔·盖茨", "era": "Modern", "type": "Entrepreneur", "career_stage": "early", "vector": {"rationality": 0.9, "ambition": 0.9, "discipline": 0.85, "risk_taking": 0.6, "creativity": 0.8, "leadership": 0.75},
     "early_career": "Dropped out of Harvard to found Microsoft with Paul Allen",
     "early_actions": "Hijacked Altair BASIC, cold-called computer companies, negotiated license deals",
     "breakthrough": "Microsoft Windows/Office - dominated PC software",
     "key_lesson": "Success is a lousy teacher. It seduces smart people into thinking they can't lose."},
    {"id": "margaret_whitney", "name": "Margaret E. Knight", "name_cn": "玛格丽特·奈特", "era": "19th Century", "type": "Inventor", "career_stage": "early", "vector": {"creativity": 0.9, "resilience": 0.95, "risk_taking": 0.6, "discipline": 0.8, "ambition": 0.7},
     "early_career": "Fled abusive home at 12, worked in cotton mill, then paper bag factory",
     "early_actions": "Invented flat-bottom paper bag machine after copying rival's design",
     "breakthrough": "Patented 22 inventions, revolutionized paper bag industry",
     "key_lesson": "Women can invent too. Study the problem deeply. Protect your ideas."},
    {"id": "colin_powell", "name": "Colin Powell", "name_cn": "科林·鲍威尔", "era": "Modern", "type": "Military/Political", "career_stage": "early", "vector": {"leadership": 0.9, "discipline": 0.95, "resilience": 0.85, "rationality": 0.8, "ambition": 0.75},
     "early_career": "NYU student, joined ROTC, commissioned as 2nd lieutenant in 1958",
     "early_actions": "Volunteered for Vietnam, climbed every rung deliberately, mentored by West Point grads",
     "breakthrough": "Chairman of Joint Chiefs, Secretary of State",
     "key_lesson": "The 40-70 rule: never go below 40% info, never wait for 70%. Delegate to empower."},
    {"id": "napoleon", "name": "Napoleon Bonaparte", "name_cn": "拿破仑·波拿巴", "era": "18th-19th Century", "type": "Military/Political", "career_stage": "early", "vector": {"ambition": 0.98, "risk_taking": 0.9, "leadership": 0.95, "rationality": 0.85, "resilience": 0.8, "discipline": 0.9},
     "early_career": "Artillery officer at 16, struggled with French accent and poverty",
     "early_actions": "Self-educated in military theory, studied geography obsessively, wrote strategy manuals",
     "breakthrough": "Conquered Europe, crowned Emperor at 35",
     "key_lesson": "Never interrupt your enemy when he is making a mistake. Speed beats brute force."},
    {"id": "abraham_lincoln", "name": "Abraham Lincoln", "name_cn": "亚伯拉罕·林肯", "era": "19th Century", "type": "Political", "career_stage": "early", "vector": {"resilience": 0.95, "discipline": 0.9, "rationality": 0.85, "empathy": 0.9, "leadership": 0.85, "ambition": 0.7},
     "early_career": "Self-taught lawyer, lost multiple elections, worked as postmaster",
     "early_actions": "Walked 16 miles to return books, studied law by candlelight, practiced debate",
     "breakthrough": "16th US President, preserved the Union, abolished slavery",
     "key_lesson": "The best way to predict the future is to create it. Keep your resolutions."},
    {"id": "clementine_churchill", "name": "Winston Churchill", "name_cn": "温斯顿·丘吉尔", "era": "19th-20th Century", "type": "Political", "career_stage": "early", "vector": {"resilience": 0.9, "ambition": 0.85, "creativity": 0.8, "risk_taking": 0.7, "leadership": 0.9, "discipline": 0.7},
     "early_career": "Failed multiple exams, joined army, reported on wars as journalist",
     "early_actions": "Studied history obsessively, wrote 8 books, practiced speeches in mirror",
     "breakthrough": "PM during WWII, led Britain through darkest hours",
     "key_lesson": "Success is stumbling from failure to failure with no loss of enthusiasm."},
    {"id": "roosevelt", "name": "Theodore Roosevelt", "name_cn": "西奥多·罗斯福", "era": "19th-20th Century", "type": "Political", "career_stage": "early", "vector": {"risk_taking": 0.9, "resilience": 0.95, "leadership": 0.9, "discipline": 0.8, "ambition": 0.85, "creativity": 0.7},
     "early_career": "Sickly child, founded Outward Bound, Harvard grad with no distinction",
     "early_actions": "Transformed weakling into athlete, wrote 14 books, explored Dakota badlands",
     "breakthrough": "26th President, built Panama Canal, won Nobel Peace Prize",
     "key_lesson": "Do what you can, with what you have, where you are. The strenuous life."},
    {"id": "franklin_roosevelt", "name": "Franklin D. Roosevelt", "name_cn": "富兰克林·罗斯福", "era": "20th Century", "type": "Political", "career_stage": "early", "vector": {"leadership": 0.9, "empathy": 0.85, "rationality": 0.8, "resilience": 0.9, "ambition": 0.8, "discipline": 0.75},
     "early_career": "Harvard student, worked NY Times, elected to Senate at 29",
     "early_actions": "Polished public speaking, built political network, contracted polio at 39",
     "breakthrough": "32nd President, New Deal, led US through Great Depression and WWII",
     "key_lesson": "The only thing we have to fear is fear itself. Do something. Anything."},
    {"id": "de_king", "name": "Martin Luther King Jr.", "name_cn": "马丁·路德·金", "era": "20th Century", "type": "Political/Social", "career_stage": "early", "vector": {"resilience": 0.95, "leadership": 0.9, "empathy": 0.95, "discipline": 0.85, "risk_taking": 0.7, "ambition": 0.8},
     "early_career": "Seminary student, PhD at 26, new to Montgomery",
     "early_actions": "Organized church networks, studied Gandhian nonviolence, practiced civil disobedience",
     "breakthrough": "Montgomery Bus Boycott, I Have a Dream, Civil Rights Act",
     "key_lesson": "Darkness cannot drive out darkness. Only light can do that."},
    {"id": "mandela", "name": "Nelson Mandela", "name_cn": "纳尔逊·曼德拉", "era": "20th Century", "type": "Political", "career_stage": "early", "vector": {"resilience": 0.98, "discipline": 0.9, "leadership": 0.9, "empathy": 0.85, "risk_taking": 0.6, "ambition": 0.75},
     "early_career": "Law student, joined ANC at 22, became underground leader",
     "early_actions": "Organized Defiance Campaign, went underground, trained with armed wing",
     "breakthrough": "27 years imprisonment, first black South African president",
     "key_lesson": "It always seems impossible until it's done. Educate yourself endlessly."},
    {"id": "galileo", "name": "Galileo Galilei", "name_cn": "伽利略·伽利莱", "era": "16th-17th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.9, "rationality": 0.9, "risk_taking": 0.7, "resilience": 0.85, "discipline": 0.7, "ambition": 0.8},
     "early_career": "Medical student, dropped out to study math, worked as tutor",
     "early_actions": "Built first telescope, calculated moon phases, challenged Aristotle openly",
     "breakthrough": "Heliocentrism, laws of motion, father of modern science",
     "key_lesson": "Measure what is measurable. Make measurable what is not."},
    {"id": "newton", "name": "Isaac Newton", "name_cn": "艾萨克·牛顿", "era": "17th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.95, "discipline": 0.9, "creativity": 0.85, "ambition": 0.7, "resilience": 0.6, "risk_taking": 0.4},
     "early_career": "Cambridge student, plague forced lockdown, isolated at Woolsthorpe",
     "early_actions": "Developed calculus, optics, gravity theory in 18 months of isolation",
     "breakthrough": "Principia Mathematica, laws of motion, universal gravitation",
     "key_lesson": "Standing on the shoulders of giants. If I have seen further..."},
    {"id": "curie", "name": "Marie Curie", "name_cn": "玛丽·居里", "era": "19th-20th Century", "type": "Scientist", "career_stage": "early", "vector": {"resilience": 0.95, "discipline": 0.95, "rationality": 0.9, "ambition": 0.85, "risk_taking": 0.5, "creativity": 0.8},
     "early_career": "Polish woman denied university, worked as governess to fund sister's education",
     "early_actions": "Moved to Paris, studied 10+ hours/day, lived on bread and butter, invented radium",
     "breakthrough": "Two Nobel Prizes, founded radiology, discovered polonium and radium",
     "key_lesson": "Nothing in life is to be feared. It is only to be understood."},
    {"id": "tesla", "name": "Nikola Tesla", "name_cn": "尼古拉·特斯拉", "era": "19th-20th Century", "type": "Inventor", "career_stage": "early", "vector": {"creativity": 0.95, "risk_taking": 0.7, "resilience": 0.75, "discipline": 0.6, "ambition": 0.8, "rationality": 0.7},
     "early_career": "Croatian engineer, immigrated to US with $4 and a letter to Edison",
     "early_actions": "Worked for Edison, designed DC motors, quit to build AC systems",
     "breakthrough": "Alternating current, radio, wireless transmission, 300+ patents",
     "key_lesson": "The present is theirs; the future, for which I really worked, is mine."},
    {"id": "edison", "name": "Thomas Edison", "name_cn": "托马斯·爱迪生", "era": "19th Century", "type": "Inventor", "career_stage": "early", "vector": {"resilience": 0.95, "discipline": 0.9, "creativity": 0.8, "risk_taking": 0.6, "ambition": 0.85, "rationality": 0.7},
     "early_career": "Self-educated, fired from jobs for 'being too slow', newspaper vendor",
     "early_actions": "Worked 18-hour days in lab, failed 10,000 times before lightbulb",
     "breakthrough": "Practical lightbulb, phonograph, motion picture camera, 1,093 patents",
     "key_lesson": "I have not failed. I've just found 10,000 ways that won't work."},
    {"id": "hedy_lamarr", "name": "Hedy Lamarr", "name_cn": "海蒂·拉玛尔", "era": "20th Century", "type": "Inventor", "career_stage": "early", "vector": {"creativity": 0.9, "risk_taking": 0.6, "ambition": 0.7, "resilience": 0.75, "discipline": 0.7, "leadership": 0.5},
     "early_career": "Austrian film star, married arms dealer, escaped to Hollywood",
     "early_actions": "Studied frequency hopping with George Antheil, patented during WW2",
     "breakthrough": "WiFi, Bluetooth foundation - 'mother of wireless'",
     "key_lesson": "Don't let others define your potential. Beauty and brains coexist."},
    {"id": "ada_lovelace", "name": "Ada Lovelace", "name_cn": " Ada 洛夫莱斯", "era": "19th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.95, "rationality": 0.85, "ambition": 0.8, "discipline": 0.7, "risk_taking": 0.5, "resilience": 0.65},
     "early_career": "Daughter of Lord Byron, mother pushed math over poetry",
     "early_actions": "Studied Babbage's Analytical Engine, translated Italian memoir with notes",
     "breakthrough": "First computer algorithm, predicted computers could compose music",
     "key_lesson": "The Analytical Engine weaves algebraic patterns."},
    {"id": "einstein", "name": "Albert Einstein", "name_cn": "阿尔伯特·爱因斯坦", "era": "20th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.98, "rationality": 0.9, "resilience": 0.7, "risk_taking": 0.6, "ambition": 0.6, "discipline": 0.5},
     "early_career": "Swiss patent clerk, PhD rejected, teaching jobs denied",
     "early_actions": "Worked patent office 9-5, published 4 papers in 1905 (annus mirabilis)",
     "breakthrough": "Relativity, E=mc², photoelectric effect, Nobel Prize 1921",
     "key_lesson": "Imagination is more important than knowledge. Question everything."},
    {"id": "darwin", "name": "Charles Darwin", "name_cn": "查尔斯·达尔文", "era": "19th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.9, "resilience": 0.8, "discipline": 0.85, "ambition": 0.7, "creativity": 0.8, "risk_taking": 0.5},
     "early_career": "Medicine student, dropped out, theology at Cambridge",
     "early_actions": "Joined Beagle voyage unpaid, collected specimens, spent 20 years researching",
     "breakthrough": "On the Origin of Species, evolution by natural selection",
     "key_lesson": "It is not the strongest that survive, but the most adaptable."},
    {"id": "hawking", "name": "Stephen Hawking", "name_cn": "斯蒂芬·霍金", "era": "20th-21st Century", "type": "Scientist", "career_stage": "early", "vector": {"resilience": 0.95, "rationality": 0.9, "creativity": 0.85, "ambition": 0.75, "discipline": 0.8, "leadership": 0.6},
     "early_career": "Oxford student, diagnosed with ALS at 21, told he had 2 years to live",
     "early_actions": "Continued studying mathematics, married Jane Wilde, had 3 children",
     "breakthrough": "Black hole radiation, singularity theorems, A Brief History of Time",
     "key_lesson": "However difficult life may seem, there is always something you can do."},
    {"id": "tesla_electric", "name": "George Westinghouse", "name_cn": "乔治·威斯汀豪斯", "era": "19th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"risk_taking": 0.85, "ambition": 0.8, "resilience": 0.75, "leadership": 0.8, "creativity": 0.7},
     "early_career": "Dropped out of college, started railroad mechanic jobs",
     "early_actions": "Invented railroad air brake at 24, sold for $1M, switched to AC current",
     "breakthrough": "Westinghouse Electric, AC power system, won War of Currents",
     "key_lesson": "Stand for what is right even when it costs you everything."},
    {"id": "ford", "name": "Henry Ford", "name_cn": "亨利·福特", "era": "19th-20th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"resilience": 0.9, "discipline": 0.85, "ambition": 0.85, "risk_taking": 0.6, "leadership": 0.75, "rationality": 0.7},
     "early_career": "Farm boy, apprentice machinist, worked for Edison, invented quadricycle at 29",
     "early_actions": "Failed twice with car companies, kept detailed notebooks, obsessed with efficiency",
     "breakthrough": "Model T, moving assembly line, $5 day wage",
     "key_lesson": "Coming together is a beginning. Staying together is progress."},
    {"id": "disney", "name": "Walt Disney", "name_cn": "沃尔特·迪士尼", "era": "20th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"creativity": 0.95, "resilience": 0.9, "ambition": 0.85, "risk_taking": 0.7, "leadership": 0.75, "discipline": 0.6},
     "early_career": "Failed cartoonist, bankrupt, ate canned bread, slept in zoo",
     "early_actions": "Walked to Hollywood with $40, drew Mickey on train, pitched to 30 studios",
     "breakthrough": "Disneyland, Mickey Mouse, animated film industry",
     "key_lesson": "All our dreams can come true if we have the courage to pursue them."},
    {"id": "pinterest_evans", "name": "Benjamin Franklin", "name_cn": "本杰明·富兰克林", "era": "18th Century", "type": "Inventor/Political", "career_stage": "early", "vector": {"creativity": 0.9, "resilience": 0.85, "ambition": 0.8, "rationality": 0.85, "discipline": 0.9, "risk_taking": 0.6},
     "early_career": "Printer's apprentice at 12, ran away to Philadelphia with $4",
     "early_actions": "Created Junto club, wrote Poor Richard's Almanack, founded library/fire dept",
     "breakthrough": "Lightning rod, bifocals, Constitution signatory, diplomacy with France",
     "key_lesson": "An investment in knowledge pays the best interest."},
    {"id": "confucius", "name": "Confucius", "name_cn": "孔子", "era": "Ancient", "type": "Philosopher", "career_stage": "early", "vector": {"discipline": 0.95, "rationality": 0.9, "empathy": 0.9, "leadership": 0.8, "resilience": 0.85, "ambition": 0.7},
     "early_career": "Orphaned young, managed warehouse and accounting at 15",
     "early_actions": "Studied ancient texts, taught privately, served as minister of justice",
     "breakthrough": "Confucianism - shaped Chinese civilization for 2,500 years",
     "key_lesson": "It does not matter how slowly you go as long as you do not stop."},
    {"id": "socrates", "name": "Socrates", "name_cn": "苏格拉底", "era": "Ancient", "type": "Philosopher", "career_stage": "early", "vector": {"rationality": 0.95, "resilience": 0.8, "discipline": 0.85, "empathy": 0.7, "leadership": 0.6, "risk_taking": 0.5},
     "early_career": "Stonecutter, served in hoplite army, studied natural philosophy",
     "early_actions": "Questioned everyone in Athens marketplace, refused to flee when sentenced",
     "breakthrough": "Socratic method, Western philosophy foundation",
     "key_lesson": "The unexamined life is not worth living."},
    {"id": "aqua", "name": "Leonardo da Vinci", "name_cn": "列奥纳多·达·芬奇", "era": "Renaissance", "type": "Artist/Scientist", "career_stage": "early", "vector": {"creativity": 0.98, "curiosity": 0.95, "resilience": 0.7, "discipline": 0.6, "ambition": 0.7, "risk_taking": 0.6},
     "early_career": "Illegitimate son, apprenticed to Verrocchio at 14",
     "early_actions": "Left notebook everywhere, studied anatomy by dissection, painted Madonna of the Rocks",
     "breakthrough": "Mona Lisa, Last Supper, flying machines, anatomical drawings",
     "key_lesson": "Learning never exhausts the mind."},
    {"id": "mozart", "name": "Wolfgang Amadeus Mozart", "name_cn": "莫扎特", "era": "18th Century", "type": "Artist", "career_stage": "early", "vector": {"creativity": 0.98, "discipline": 0.9, "ambition": 0.7, "risk_taking": 0.5, "resilience": 0.6, "rationality": 0.6},
     "early_career": "Child prodigy, toured Europe at age 6, composed at 8",
     "early_actions": "Played for royalty, studied counterpoint obsessively, wrote 600+ works",
     "breakthrough": "Requiem, Don Giovanni, Magic Flute, 41 symphonies",
     "key_lesson": "The music is not in the notes, but in the silence between."},
    {"id": "beethoven", "name": "Ludwig van Beethoven", "name_cn": "贝多芬", "era": "18th-19th Century", "type": "Artist", "career_stage": "early", "vector": {"resilience": 0.95, "discipline": 0.9, "ambition": 0.85, "creativity": 0.9, "risk_taking": 0.6, "leadership": 0.7},
     "early_career": "Studied under Haydn in Vienna, deafness began at 26",
     "early_actions": "Composed while losing hearing, communicated via books, refused to quit",
     "breakthrough": "9 symphonies, 32 piano sonatas, Fidelio, Missa Solemnis",
     "key_lesson": "I will take fate by the throat. It shall not wholly crush me."},
    {"id": "shakespeare", "name": "William Shakespeare", "name_cn": "威廉·莎士比亚", "era": "16th-17th Century", "type": "Artist", "career_stage": "early", "vector": {"creativity": 0.98, "ambition": 0.8, "resilience": 0.7, "risk_taking": 0.6, "discipline": 0.6, "leadership": 0.5},
     "early_career": "Stratford grammar school, married at 18, left for London as 'whipping boy'",
     "early_actions": "Joined acting company, wrote plays for Globe Theatre, bought Stratford estate",
     "breakthrough": "37 plays, 154 sonnets, transformed English language",
     "key_lesson": "All the world's a stage, and all the men and women merely players."},
    {"id": "miguel_de_cervantes", "name": "Miguel de Cervantes", "name_cn": "塞万提斯", "era": "16th-17th Century", "type": "Artist", "career_stage": "early", "vector": {"resilience": 0.95, "risk_taking": 0.8, "ambition": 0.7, "discipline": 0.7, "leadership": 0.6, "empathy": 0.8},
     "early_career": "Soldier at Lepanto (lost arm), captured by pirates, 5 years as slave",
     "early_actions": "Prisoner writing, worked multiple jobs, studied human nature deeply",
     "breakthrough": "Don Quixote - first modern novel",
     "key_lesson": "The pen is the tongue of the mind."},
    {"id": "leo_tolstoy", "name": "Leo Tolstoy", "name_cn": "列夫·托尔斯泰", "era": "19th Century", "type": "Artist", "career_stage": "early", "vector": {"discipline": 0.9, "rationality": 0.85, "empathy": 0.8, "resilience": 0.7, "ambition": 0.7, "creativity": 0.9},
     "early_career": "Noble family, lost parents young, failed exams, ran away to Paris",
     "early_actions": "Joined army in Caucasus, wrote War and Peace over 6 years, founded school for peasants",
     "breakthrough": "War and Peace, Anna Karenina, philosophical reformer",
     "key_lesson": "The two most powerful warriors are patience and time."},
    {"id": "victor_hugo", "name": "Victor Hugo", "name_cn": "维克多·雨果", "era": "19th Century", "type": "Artist", "career_stage": "early", "vector": {"creativity": 0.95, "resilience": 0.85, "ambition": 0.8, "risk_taking": 0.7, "empathy": 0.85, "discipline": 0.6},
     "early_career": "Child prodigy writer, exiled for 19 years for opposing Napoleon III",
     "early_actions": "Wrote in exile, built prison in garden, wrote Les Misérables over 20 years",
     "breakthrough": "Les Misérables, Hunchback of Notre Dame, abolished death penalty",
     "key_lesson": "Even the smallest person can change the course of history."},
    {"id": "dostoevsky", "name": "Fyodor Dostoevsky", "name_cn": "陀思妥耶夫斯基", "era": "19th Century", "type": "Artist", "career_stage": "early", "vector": {"resilience": 0.95, "empathy": 0.9, "rationality": 0.8, "ambition": 0.75, "discipline": 0.7, "risk_taking": 0.5},
     "early_career": "Military engineer, arrested for printing circle, simulated execution",
     "early_actions": "Siberian prison 4 years, gambling addiction, wrote from death row perspective",
     "breakthrough": "Crime and Punishment, Brothers Karamazov, explored psychology of guilt",
     "key_lesson": "Pain and suffering are always inevitable."},
    {"id": "marx", "name": "Karl Marx", "name_cn": "卡尔·马克思", "era": "19th Century", "type": "Philosopher/Political", "career_stage": "early", "vector": {"rationality": 0.9, "resilience": 0.85, "ambition": 0.8, "discipline": 0.75, "risk_taking": 0.6, "empathy": 0.7},
     "early_career": "Law student, PhD from Jena, moved to Paris, met Engels",
     "early_actions": "Exiled from multiple countries, wrote Communist Manifesto in London library",
     "breakthrough": "Das Kapital, Marxism, shaped 20th century politics",
     "key_lesson": "Philosophers have only interpreted the world. The point is to change it."},
    {"id": "machu_picchu", "name": "Inca Civilization", "name_cn": "印加文明", "era": "Ancient", "type": "Builder", "career_stage": "early", "vector": {"discipline": 0.95, "leadership": 0.85, "creativity": 0.7, "resilience": 0.8, "rationality": 0.7, "ambition": 0.75},
     "early_career": "Valley of Cusco, small kingdom building trade routes",
     "early_actions": "Built road system 25,000 miles, terraced mountains, quipu recording system",
     "breakthrough": "Machu Picchu, largest empire in pre-Columbian America",
     "key_lesson": "Work together. Plan for generations."},
    {"id": "cleopatra", "name": "Cleopatra VII", "name_cn": "克莉奥佩特拉七世", "era": "Ancient", "type": "Political", "career_stage": "early", "vector": {"leadership": 0.9, "risk_taking": 0.8, "ambition": 0.95, "rationality": 0.85, "resilience": 0.8, "creativity": 0.7},
     "early_career": "Youngest pharaoh, exiled by brothers, gathered loyalists",
     "early_actions": "Rolled in carpet to meet Caesar, learned 7 languages, studied astronomy",
     "breakthrough": "Last active pharaoh, allied with Rome's greatest men",
     "key_lesson": "Opportunity does not knock. It presents itself when you minimize waste."},
    {"id": "genghis_khan", "name": "Genghis Khan", "name_cn": "成吉思汗", "era": "12th-13th Century", "type": "Military/Political", "career_stage": "early", "vector": {"risk_taking": 0.95, "leadership": 0.95, "resilience": 0.9, "ambition": 0.98, "discipline": 0.7, "rationality": 0.65},
     "early_career": "Father poisoned, family exiled, killed half-brother for food",
     "early_actions": "Allied with Toghrul, rebuilt army from 20 horses, adopted meritocracy",
     "breakthrough": "Largest contiguous land empire in history",
     "key_lesson": "One dispersion of the arrows is worth a thousand gatherings."},
    {"id": "gates_warren", "name": "Andrew Carnegie", "name_cn": "安德鲁·卡内基", "era": "19th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"ambition": 0.9, "resilience": 0.85, "risk_taking": 0.7, "discipline": 0.8, "leadership": 0.75},
     "early_career": "Pennsylvania Railroad telegrapher at 13, $1.20/week",
     "early_actions": "Self-educated, studied steel industry, invested in bridges and oil",
     "breakthrough": "Carnegie Steel - produced more steel than Britain",
     "key_lesson": "The man who dies rich dies disgraced."},
    {"id": "rocks_feller", "name": "Rockefeller", "name_cn": "洛克菲勒", "era": "19th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"discipline": 0.95, "rationality": 0.9, "resilience": 0.8, "ambition": 0.85, "risk_taking": 0.5},
     "early_career": "Bookkeeper at 16, studied accounting obsessively",
     "early_actions": "Kept perfect records, reinvested profits, studied competitors' weaknesses",
     "breakthrough": "Standard Oil - 90% of US refining",
     "key_lesson": "Build systems that work without you."},
    {"id": "graham_benjamin", "name": "Benjamin Graham", "name_cn": "本杰明·格雷厄姆", "era": "20th Century", "type": "Investor", "career_stage": "early", "vector": {"rationality": 0.95, "discipline": 0.9, "resilience": 0.7, "ambition": 0.6, "risk_taking": 0.3, "creativity": 0.7},
     "early_career": "Columbia MBA, survived 1929 crash losing 68%",
     "early_actions": "Wrote Security Analysis, taught at Columbia, mentored future investors",
     "breakthrough": "Value investing philosophy, father of Wall Street wisdom",
     "key_lesson": "The intelligent investor is an realist who sells to optimists and buys from pessimists."},
    {"id": "seagram_jesse", "name": "Jesse Livermore", "name_cn": "杰西·利弗莫尔", "era": "Early 20th Century", "type": "Trader", "career_stage": "early", "vector": {"risk_taking": 0.95, "resilience": 0.7, "discipline": 0.5, "rationality": 0.7, "ambition": 0.9, "creativity": 0.6},
     "early_career": "14 years old ticking prices on stock ticker, worked bucket shops",
     "early_actions": "Kept trading journal, learned tape reading, made $100K at 24",
     "breakthrough": "Made and lost $100M multiple times, wrote How to Trade in Stocks",
     "key_lesson": "The market is never wrong. Opinions often are."},
    {"id": "louis_banana", "name": "Louis B. Mayer", "name_cn": "路易斯·B·梅耶", "era": "20th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"ambition": 0.85, "risk_taking": 0.7, "leadership": 0.8, "resilience": 0.8, "discipline": 0.6, "creativity": 0.7},
     "early_career": "Jewish immigrant from Lithuania, started in clothing business",
     "early_actions": "Opened vaudeville theaters, moved to Hollywood, built MGM from scratch",
     "breakthrough": "MGM - golden age of Hollywood",
     "key_lesson": "Give the public what they want before they know they want it."},
    {"id": "steinem_gloria", "name": "Gloria Steinem", "name_cn": "格洛丽亚·斯坦纳姆", "era": "20th Century", "type": "Activist", "career_stage": "early", "vector": {"resilience": 0.9, "ambition": 0.8, "risk_taking": 0.7, "empathy": 0.9, "leadership": 0.85, "discipline": 0.7},
     "early_career": "Journalist, undercover at Playboy to expose sexism",
     "early_actions": "Co-founded Ms. Magazine, organized women's rights movement",
     "breakthrough": "Feminist icon, transformed American gender politics",
     "key_lesson": "The story of women's oppression is written in code: the alphabet of tyranny."},
    {"id": "rice_jesse", "name": "Jesse Jackson", "name_cn": "杰西·杰克逊", "era": "20th Century", "type": "Activist", "career_stage": "early", "vector": {"resilience": 0.85, "leadership": 0.9, "risk_taking": 0.7, "empathy": 0.8, "ambition": 0.75, "discipline": 0.7},
     "early_career": "Black preacher's son, integrated Northwestern, arrested at sit-ins",
     "early_actions": "Organized Operation Breadbasket, ran for president twice",
     "breakthrough": "Civil rights leader, brought economic justice to forefront",
     "key_lesson": " The arc of the moral universe is long but it bends toward justice."},
    {"id": "jones_seoul", "name": "Seoul's Development", "name_cn": "首尔发展经验", "era": "Modern", "type": "Builder", "career_stage": "early", "vector": {"discipline": 0.9, "leadership": 0.85, "rationality": 0.8, "ambition": 0.85, "resilience": 0.8, "risk_taking": 0.6},
     "early_career": "Destroyed by Korean War, 1960 GDP below many African nations",
     "early_actions": "Export-oriented industrialization, education investment, chaebol partnerships",
     "breakthrough": "From poverty to G20 economy in one generation",
     "key_lesson": "Education is the great equalizer."},
    {"id": "singapore_lee", "name": "Lee Kuan Yew", "name_cn": "李光耀", "era": "20th Century", "type": "Political", "career_stage": "early", "vector": {"rationality": 0.95, "discipline": 0.95, "resilience": 0.85, "ambition": 0.8, "leadership": 0.9, "risk_taking": 0.5},
     "early_career": "British-educated lawyer, entered politics when Singapore isolated",
     "early_actions": "Negotiated independence, expelled communists, built port from nothing",
     "breakthrough": "Singapore - from Third World to First in one generation",
     "key_lesson": "Hard work, discipline, and integrity are the keys to success."},
    {"id": "india_gandhi", "name": "Mahatma Gandhi", "name_cn": "圣雄甘地", "era": "19th-20th Century", "type": "Activist", "career_stage": "early", "vector": {"resilience": 0.98, "discipline": 0.95, "empathy": 0.95, "rationality": 0.8, "risk_taking": 0.6, "leadership": 0.85},
     "early_career": "Failed lawyer in India, discriminated against in South Africa",
     "early_actions": "Developed satyagraha (truth force), organized Indian community, studied law in London",
     "breakthrough": "Indian independence through nonviolent resistance",
     "key_lesson": "Be the change you wish to see in the world."},
    {"id": "buddha", "name": "Siddhartha Gautama", "name_cn": "释迦牟尼", "era": "Ancient", "type": "Philosopher", "career_stage": "early", "vector": {"resilience": 0.9, "discipline": 0.95, "empathy": 0.95, "rationality": 0.85, "ambition": 0.5, "leadership": 0.7},
     "early_career": "Prince raised in luxury, saw suffering outside palace walls",
     "early_actions": "Renounced throne, studied asceticism, meditated 6 years under Bodhi tree",
     "breakthrough": "Buddhism - Four Noble Truths, Eightfold Path",
     "key_lesson": "The root of suffering is attachment."},
    {"id": "lao_tzu", "name": "Lao Tzu", "name_cn": "老子", "era": "Ancient", "type": "Philosopher", "career_stage": "early", "vector": {"rationality": 0.9, "discipline": 0.8, "empathy": 0.85, "resilience": 0.7, "ambition": 0.4, "creativity": 0.9},
     "early_career": "Archivist for Zhou dynasty, grew disillusioned with court politics",
     "early_actions": "Wrote Tao Te Ching at border, rode water buffalo into exile",
     "breakthrough": "Taoism - way of simplicity and harmony",
     "key_lesson": "The journey of a thousand miles begins with one step."},
    {"id": "machiavelli", "name": "Niccolò Machiavelli", "name_cn": "马基雅维利", "era": "Renaissance", "type": "Philosopher/Political", "career_stage": "early", "vector": {"rationality": 0.9, "resilience": 0.85, "ambition": 0.7, "risk_taking": 0.6, "discipline": 0.75, "leadership": 0.6},
     "early_career": "Florentine diplomat, tortured and exiled by Medici family",
     "early_actions": "Wrote The Prince in isolation, studied Roman history obsessively",
     "breakthrough": "Founder of modern political science",
     "key_lesson": "It is better to be feared than loved, if you cannot be both."},
    {"id": "hobbes", "name": "Thomas Hobbes", "name_cn": "托马斯·霍布斯", "era": "17th Century", "type": "Philosopher", "career_stage": "early", "vector": {"rationality": 0.9, "discipline": 0.85, "resilience": 0.7, "ambition": 0.6, "creativity": 0.7, "risk_taking": 0.4},
     "early_career": "Tutor to Cavendish family, exiled to Paris during Civil War",
     "early_actions": "Wrote Leviathan during exile, studied history and geometry",
     "breakthrough": "Social contract theory, modern political philosophy",
     "key_lesson": "The life of man is solitary, poor, nasty, brutish, and short."},
    {"id": "locke_john", "name": "John Locke", "name_cn": "约翰·洛克", "era": "17th Century", "type": "Philosopher", "career_stage": "early", "vector": {"rationality": 0.95, "discipline": 0.85, "resilience": 0.8, "ambition": 0.6, "creativity": 0.7, "empathy": 0.75},
     "early_career": "Oxford student, studied medicine, exiled to Netherlands",
     "early_actions": "Wrote Two Treatises of Government in hiding, studied medicine and philosophy",
     "breakthrough": "Father of liberalism, natural rights theory",
     "key_lesson": "Tabula rasa - the mind is a blank slate at birth."},
    {"id": "rousseau", "name": "Jean-Jacques Rousseau", "name_cn": "卢梭", "era": "18th Century", "type": "Philosopher", "career_stage": "early", "vector": {"creativity": 0.85, "resilience": 0.8, "ambition": 0.7, "risk_taking": 0.5, "empathy": 0.8, "discipline": 0.6},
     "early_career": "Born in Geneva, ran away at 15, worked as apprentice, servant, tutor",
     "early_actions": "Wrote Discourse on Inequality, studied music and philosophy",
     "breakthrough": "Social contract theory, influenced French Revolution",
     "key_lesson": "Man is born free, and everywhere he is in chains."},
    {"id": "volta", "name": "Alessandro Volta", "name_cn": "亚历山德罗·伏打", "era": "18th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.9, "discipline": 0.85, "resilience": 0.75, "creativity": 0.8, "ambition": 0.7, "risk_taking": 0.5},
     "early_career": "Priest's son, studied at Jesuit school, discovered electricity",
     "early_actions": "Built first battery (voltaic pile), invented electrophorus",
     "breakthrough": "Electric battery, unit 'volt' named after him",
     "key_lesson": "The greatest discoveries are made by patient observation."},
    {"id": "faraday", "name": "Michael Faraday", "name_cn": "迈克尔·法拉第", "era": "19th Century", "type": "Scientist", "career_stage": "early", "vector": {"resilience": 0.9, "creativity": 0.85, "rationality": 0.85, "discipline": 0.8, "ambition": 0.7, "risk_taking": 0.5},
     "early_career": "Bookbinder's apprentice, self-educated from books he bound",
     "early_actions": "Attended lectures by Sir Humphry Davy, sent him notes, got job as lab assistant",
     "breakthrough": "Electromagnetic rotation, faraday cage, electromagnetic induction",
     "key_lesson": "Nothing is too wonderful to be true."},
    {"id": "bose", "name": "Jagadish Chandra Bose", "name_cn": "贾格迪什·钱德拉·玻色", "era": "19th-20th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.9, "resilience": 0.85, "rationality": 0.8, "discipline": 0.85, "ambition": 0.7, "risk_taking": 0.5},
     "early_career": "Studied in London while training as doctor, faced racism",
     "early_actions": "Built wireless devices, proved plants have sensitivity, studied microwaves",
     "breakthrough": "Radio waves, plant physiology, millimeter waves",
     "key_lesson": "Nature is one. We are all connected."},
    {"id": "srinivasa_ramanujan", "name": "Srinivasa Ramanujan", "name_cn": "拉马努金", "era": "Early 20th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.98, "rationality": 0.7, "resilience": 0.8, "ambition": 0.6, "discipline": 0.5, "risk_taking": 0.4},
     "early_career": "Self-taught mathematician from India, no formal training",
     "early_actions": "Wrote 3,900 results in notebook, mailed to Cambridge, G.H. Hardy replied",
     "breakthrough": "Infinite series, partition theory, mock theta functions",
     "key_lesson": "An equation for me has no meaning unless it expresses a thought of God."},
    {"id": "lovelace", "name": "Charles Babbage", "name_cn": "查尔斯·巴贝奇", "era": "19th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.9, "rationality": 0.85, "resilience": 0.6, "ambition": 0.7, "discipline": 0.7, "risk_taking": 0.5},
     "early_career": "Cambridge student, founded Analytical Society",
     "early_actions": "Designed Difference Engine, proposed Analytical Engine, studied statistics",
     "breakthrough": "Father of computing, first conceptual computer",
     "key_lesson": "The steam engine may do for physical things what calculating engines do for moral ones."},
    {"id": "shannon", "name": "Claude Shannon", "name_cn": "克劳德·香农", "era": "20th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.95, "rationality": 0.9, "resilience": 0.7, "ambition": 0.6, "discipline": 0.6, "risk_taking": 0.5},
     "early_career": "MIT undergrad, played clarinet in university band",
     "early_actions": "Wrote thesis on relay circuits, connected Boolean algebra to switches",
     "breakthrough": "Information theory, digital circuit design foundation",
     "key_lesson": "The underlying message of 50 years of scientific work is to be admired, not imitated."},
    {"id": "turing", "name": "Alan Turing", "name_cn": "艾伦·图灵", "era": "20th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.95, "creativity": 0.9, "resilience": 0.6, "discipline": 0.7, "ambition": 0.6, "risk_taking": 0.5},
     "early_career": "Self-taught programmer, cracked Enigma at Bletchley Park",
     "early_actions": "Built Bombe machine, studied artificial intelligence, wrote Computing Machinery",
     "breakthrough": "Turing machine, AI founder, cracked Nazi codes saving millions",
     "key_lesson": "We can only see a short distance ahead, but we can see plenty there that needs to be done."},
    {"id": "von_neumann", "name": "John von Neumann", "name_cn": "冯·诺依曼", "era": "20th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.98, "creativity": 0.85, "discipline": 0.8, "ambition": 0.7, "resilience": 0.6, "risk_taking": 0.5},
     "early_career": "Child prodigy, memorized telephone directory at 6, fluent in Greek/Latin",
     "early_actions": "Worked on quantum mechanics, game theory, set theory simultaneously",
     "breakthrough": "von Neumann architecture, Monte Carlo method, game theory",
     "key_lesson": "The true delight is in the finding out rather than in the knowing."},
    {"id": "bohr", "name": "Niels Bohr", "name_cn": "尼尔斯·玻尔", "era": "20th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.95, "creativity": 0.85, "discipline": 0.8, "resilience": 0.75, "ambition": 0.7, "risk_taking": 0.5},
     "early_career": "Danish student, walked 8 miles daily to university",
     "early_actions": "Studied electron behavior, won Nobel at 31, hosted physics institute",
     "breakthrough": "Atomic structure, quantum mechanics, nuclear fission prediction",
     "key_lesson": "Every atom in our bodies was torn from a star."},
    {"id": "heisenberg", "name": "Werner Heisenberg", "name_cn": "维尔纳·海森堡", "era": "20th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.95, "creativity": 0.9, "discipline": 0.75, "resilience": 0.7, "ambition": 0.7, "risk_taking": 0.5},
     "early_career": "University student, worked with Sommerfeld, developed matrix mechanics",
     "early_actions": "Formulated uncertainty principle, won Nobel at 32",
     "breakthrough": "Uncertainty principle, quantum mechanics foundation",
     "key_lesson": "The observable only is real."},
    {"id": "planck", "name": "Max Planck", "name_cn": "马克斯·普朗克", "era": "19th-20th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.95, "discipline": 0.9, "resilience": 0.75, "ambition": 0.6, "creativity": 0.8, "risk_taking": 0.4},
     "early_career": "University student, studied thermodynamics, questioned classical physics",
     "early_actions": "Developed quantum theory, won Nobel, survived WWII bombing",
     "breakthrough": "Quantum theory, Planck's constant, photoelectric effect explanation",
     "key_lesson": "Science cannot solve the ultimate mystery of nature."},
    {"id": "rutherford", "name": "Ernest Rutherford", "name_cn": "欧内斯特·卢瑟福", "era": "19th-20th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.9, "resilience": 0.8, "discipline": 0.85, "creativity": 0.75, "ambition": 0.7, "risk_taking": 0.5},
     "early_career": "Farming boy in New Zealand, won scholarship to university",
     "early_actions": "Studied electricity, discovered radioactive elements, won Nobel in Chemistry",
     "breakthrough": "Nuclear physics, proton discovery, atomic model",
     "key_lesson": "If it can't be measured, it doesn't exist."},
    {"id": "pasteur", "name": "Louis Pasteur", "name_cn": "路易·巴斯德", "era": "19th Century", "type": "Scientist", "career_stage": "early", "vector": {"resilience": 0.9, "discipline": 0.85, "rationality": 0.85, "creativity": 0.8, "ambition": 0.7, "risk_taking": 0.5},
     "early_career": "Poor student, teacher said 'never amount to anything'",
     "early_actions": "Studied chemistry, discovered molecular asymmetry, developed pasteurization",
     "breakthrough": "Germ theory, vaccines for rabies and anthrax",
     "key_lesson": "Chance favors the prepared mind."},
    {"id": "jenner", "name": "Edward Jenner", "name_cn": "爱德华·詹纳", "era": "18th Century", "type": "Scientist", "career_stage": "early", "vector": {"resilience": 0.85, "rationality": 0.8, "discipline": 0.8, "creativity": 0.75, "ambition": 0.6, "risk_taking": 0.7},
     "early_career": "Apprenticed to surgeon at 14, studied in London",
     "early_actions": "Observed milkmaids who got cowpox were immune to smallpox, tested on boy",
     "breakthrough": "Smallpox vaccine - saved millions of lives",
     "key_lesson": "Patience and observation solve most problems."},
    {"id": "fisher", "name": "Ronald Fisher", "name_cn": "罗纳德·费舍尔", "era": "20th Century", "type": "Scientist", "career_stage": "early", "vector": {"rationality": 0.95, "discipline": 0.85, "creativity": 0.8, "resilience": 0.7, "ambition": 0.6, "risk_taking": 0.5},
     "early_career": "Self-taught mathematician, worked at Rothamsted experimental station",
     "early_actions": "Developed statistical methods, unified genetics and evolution",
     "breakthrough": "Modern statistics, evolutionary synthesis",
     "key_lesson": "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge."},
    {"id": "mendel", "name": "Gregor Mendel", "name_cn": "格雷戈尔·孟德尔", "era": "19th Century", "type": "Scientist", "career_stage": "early", "vector": {"discipline": 0.95, "resilience": 0.8, "rationality": 0.85, "creativity": 0.7, "ambition": 0.5, "risk_taking": 0.3},
     "early_career": "Monk in Brno, studied mathematics and physics",
     "early_actions": "Grew 28,000 pea plants over 8 years, tracked inheritance patterns",
     "breakthrough": "Laws of inheritance, father of genetics",
     "key_lesson": "The laws of nature are simple and elegant."},
    {"id": "hooke", "name": "Robert Hooke", "name_cn": "罗伯特·胡克", "era": "17th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.9, "rationality": 0.85, "discipline": 0.75, "resilience": 0.6, "ambition": 0.7, "risk_taking": 0.5},
     "early_career": "Oxford student, worked with Boyle, built microscope",
     "early_actions": "Discovered cells, studied elasticity, designed astronomical instruments",
     "breakthrough": "Micrographia, Hooke's law, cell theory",
     "key_lesson": "No one man should have all the power."},
    {"id": "wilson_helen", "name": "Helen Keller", "name_cn": "海伦·凯勒", "era": "19th-20th Century", "type": "Activist", "career_stage": "early", "vector": {"resilience": 0.98, "discipline": 0.95, "ambition": 0.8, "risk_taking": 0.6, "empathy": 0.9, "leadership": 0.75},
     "early_career": "Deaf and blind at 19 months, tantrums, isolated from world",
     "early_actions": "Learned to communicate with Anne Sullivan, studied at Radcliffe",
     "breakthrough": "First deaf-blind person to earn BA, activist for disabled rights",
     "key_lesson": "Optimism is the faith that leads to achievement."},
    {"id": "roosevelt_eleanor", "name": "Eleanor Roosevelt", "name_cn": "埃莉诺·罗斯福", "era": "20th Century", "type": "Activist", "career_stage": "early", "vector": {"resilience": 0.9, "empathy": 0.9, "leadership": 0.85, "ambition": 0.75, "discipline": 0.7, "risk_taking": 0.65},
     "early_career": "Orphaned young, shy, taught at school for girls",
     "early_actions": "Married cousin Franklin, entered politics, wrote newspaper column",
     "breakthrough": "First Lady, UN delegate, drafted Universal Declaration of Human Rights",
     "key_lesson": "The future belongs to those who believe in the beauty of their dreams."},
    {"id": "thomas_edison_child", "name": "Thomas Edison (Youth)", "name_cn": "爱迪生(青年)", "era": "19th Century", "type": "Inventor", "career_stage": "early", "vector": {"resilience": 0.95, "discipline": 0.9, "creativity": 0.8, "ambition": 0.85, "risk_taking": 0.6, "rationality": 0.7},
     "early_career": "Homeschooled by mother after teacher called him 'too slow'",
     "early_actions": "Built chemistry lab in basement, sold newspapers on trains, invented stock ticker",
     "breakthrough": "1,093 patents, phonograph, lightbulb, motion pictures",
     "key_lesson": "Genius is 1% inspiration and 99% perspiration."},
    {"id": "edison_young", "name": "Alexander Graham Bell", "name_cn": "亚历山大·格雷厄姆·贝尔", "era": "19th Century", "type": "Inventor", "career_stage": "early", "vector": {"creativity": 0.9, "resilience": 0.8, "rationality": 0.8, "ambition": 0.7, "discipline": 0.7, "risk_taking": 0.6},
     "early_career": "Born in Scotland, mother and wife were deaf, studied speech",
     "early_actions": "Invented photophone, raced Elisha Gray to patent office, made first call",
     "breakthrough": "Telephone, audiometer, flight experiments",
     "key_lesson": "Leave the way you found it - cleaner than you found it."},
    {"id": "wright", "name": "Wright Brothers", "name_cn": "莱特兄弟", "era": "Early 20th Century", "type": "Inventors", "career_stage": "early", "vector": {"resilience": 0.9, "discipline": 0.85, "creativity": 0.9, "rationality": 0.85, "ambition": 0.7, "risk_taking": 0.7},
     "early_career": "Bicycle shop owners, self-taught aviators",
     "early_actions": "Built wind tunnel, studied bird flight, tested 200+ wing designs",
     "breakthrough": "First powered flight at Kitty Hawk, 12 seconds that changed the world",
     "key_lesson": "Life is either a daring adventure or nothing at all."},
    {"id": "marconi", "name": "Guglielmo Marconi", "name_cn": "古列尔莫·马可尼", "era": "Late 19th Century", "type": "Inventor", "career_stage": "early", "vector": {"creativity": 0.85, "resilience": 0.8, "ambition": 0.75, "risk_taking": 0.7, "discipline": 0.6, "rationality": 0.7},
     "early_career": "Self-taught physicist, father's estate in Italy",
     "early_actions": "Experimented with wireless signals, crossed Atlantic at great risk",
     "breakthrough": "Radio communication, Nobel Prize 1909",
     "key_lesson": "Physics is the only science in which nobody ever makes a mistake first time."},
    {"id": "daguerre", "name": "Louis Daguerre", "name_cn": "路易·达盖尔", "era": "19th Century", "type": "Artist/Scientist", "career_stage": "early", "vector": {"creativity": 0.9, "discipline": 0.75, "ambition": 0.7, "resilience": 0.7, "risk_taking": 0.5, "rationality": 0.65},
     "early_career": "Theater scenery painter, studied with Caproni",
     "early_actions": "Invented daguerreotype, experimented with silver and iodine",
     "breakthrough": "First practical photograph, gave invention to world freely",
     "key_lesson": "Art without science is blind; science without art is lame."},
    {"id": "niepce", "name": "Nicéphore Niépce", "name_cn": "尼埃普斯", "era": "19th Century", "type": "Scientist", "career_stage": "early", "vector": {"creativity": 0.85, "discipline": 0.7, "resilience": 0.8, "ambition": 0.6, "risk_taking": 0.5, "rationality": 0.7},
     "early_career": "Inherited estate, studied chemistry and physics",
     "early_actions": "Experimented with light-sensitive materials, made first permanent photograph",
     "breakthrough": "Heliography, first photograph 'View from the Window at Le Gras'",
     "key_lesson": "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away."},
    {"id": "daguerre_2", "name": "Robert Falcon Scott", "name_cn": "罗伯特·法尔肯·斯科特", "era": "Early 20th Century", "type": "Explorer", "career_stage": "early", "vector": {"resilience": 0.95, "discipline": 0.9, "risk_taking": 0.7, "leadership": 0.8, "ambition": 0.7, "rationality": 0.65},
     "early_career": "Royal Navy officer, joined Antarctic expedition at 28",
     "early_actions": "Marched to South Pole, died on return with 4 companions",
     "breakthrough": "British Antarctic Expedition, scientific discoveries",
     "key_lesson": "Hardship, danger, and struggle are the price of all great achievements."},
    {"id": "shackleton", "name": "Ernest Shackleton", "name_cn": "欧内斯特·沙克尔顿", "era": "Early 20th Century", "type": "Explorer", "career_stage": "early", "vector": {"resilience": 0.98, "leadership": 0.95, "discipline": 0.9, "ambition": 0.8, "risk_taking": 0.7, "empathy": 0.85},
     "early_career": "Royal Navy, joined Antarctic expedition, failed to reach South Pole",
     "early_actions": "Endurance expedition sank, led 28 men across ice and sea to safety",
     "breakthrough": "All 28 men survived impossible odds",
     "key_lesson": "Leadership is ordering others to do things that would make you do them first."},
    {"id": "amundsen", "name": "Roald Amundsen", "name_cn": "罗阿尔德·阿蒙森", "era": "Early 20th Century", "type": "Explorer", "career_stage": "early", "vector": {"resilience": 0.9, "discipline": 0.95, "risk_taking": 0.7, "leadership": 0.85, "ambition": 0.8, "rationality": 0.85},
     "early_career": "Norwegian sailor, trained with Inuit, studied polar exploration",
     "early_actions": "First to South Pole, first Northwest Passage, learned from indigenous people",
     "breakthrough": "Polar exploration records, disappeared searching for North Pole",
     "key_lesson": "Victory awaits him who has everything in order - luck, he knows, is not one of them."},
    {"id": "cook", "name": "Robert Peary", "name_cn": "罗伯特·皮里", "era": "Early 20th Century", "type": "Explorer", "career_stage": "early", "vector": {"risk_taking": 0.85, "resilience": 0.8, "ambition": 0.9, "leadership": 0.75, "discipline": 0.7, "rationality": 0.65},
     "early_career": "Naval Academy graduate, surveyed in Greenland",
     "early_actions": "Made 6 expeditions to Arctic, trained with Inuit",
     "breakthrough": "Claimed North Pole, though disputed",
     "key_lesson": "The Arctic is a land of opportunity for the persistent."},
    {"id": "ferrari_enzo", "name": "Enzo Ferrari", "name_cn": "恩佐·法拉利", "era": "20th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"ambition": 0.95, "risk_taking": 0.8, "resilience": 0.85, "discipline": 0.75, "leadership": 0.7, "creativity": 0.7},
     "early_career": "Raced cars for Alfa Romeo, crashed and nearly died",
     "early_actions": "Founded Scuderia Ferrari, built race cars, lost everything in WWII bombing",
     "breakthrough": "Ferrari - most iconic sports car brand",
     "key_lesson": "I don't sell cars. I sell dreams."},
    {"id": "kroc_ray", "name": "Ray Kroc", "name_cn": "雷·克洛克", "era": "20th Century", "type": "Entrepreneur", "career_stage": "early", "vector": {"resilience": 0.95, "ambition": 0.9, "discipline": 0.8, "risk_taking": 0.7, "leadership": 0.75, "creativity": 0.6},
     "early_career": "Milkshake mixer salesman at 22, sold paper cups, failed multiple businesses",
     "early_actions": "Found McDonald's at 52, bought franchise, built empire over 40 years",
     "breakthrough": "McDonald's - 35,000+ restaurants worldwide",
     "key_lesson": "Most people overestimate what they can do in one year and underestimate what they can do in ten years."},
    {"id": "orville_wright", "name": "Orville Wright", "name_cn": "奥维尔·莱特", "era": "Early 20th Century", "type": "Inventor", "career_stage": "early", "vector": {"resilience": 0.9, "discipline": 0.85, "creativity": 0.9, "rationality": 0.85, "ambition": 0.7, "risk_taking": 0.7},
     "early_career": "Newspaper printer, bicycle mechanic, self-taught aerodynamics",
     "early_actions": "Built wind tunnel, tested gliders, designed control system",
     "breakthrough": "First powered flight with brother Wilbur",
     "key_lesson": "The dream is not always the thing we see, but the question we ask."},
]

with open("/c/Users/Pactera/projects/careercourse/src/data/figures.json", "w", encoding="utf-8") as f:
    json.dump(FIGURES, f, ensure_ascii=False, indent=2)

print(f"Created {len(FIGURES)} figures")
