"""Add more historical figures to fill remaining placeholders"""
import json
from pathlib import Path

BASE = Path(r"E:\aiprojects\tinyapp\career_course")
figs_file = BASE / "src/data/figures.json"

with open(figs_file, encoding="utf-8") as f:
    data = json.load(f)

figures = data["figures"]

# Find remaining placeholders
placeholders = [(i, f) for i, f in enumerate(figures) if "历史人物" in f.get("name_cn", "")]
print(f"Found {len(placeholders)} remaining placeholders")

# More historical figures to add
MORE_FIGURES = [
    {"name": "Benjamin Franklin", "name_cn": "富兰克林", "era": "启蒙时代", "type": "科学家",
     "vector": [0.9, 0.8, 0.7, 0.8, 0.3, 0.7, 0.8, 0.85, 0.75, 0.7, 0.75, 0.8],
     "early_career": "印刷工出身，自学科学",
     "early_actions": "风筝实验证明雷电本质，创立图书馆",
     "breakthrough": "发明避雷针，参与美国独立宣言",
     "key_lesson": "知识就是力量"},
    {"name": "Leonardo Da Vinci", "name_cn": "达芬奇", "era": "文艺复兴", "type": "艺术家",
     "vector": [0.95, 0.85, 0.7, 0.8, 0.3, 0.6, 0.7, 0.9, 0.7, 0.8, 0.9, 0.8],
     "early_career": "学徒于韦罗基奥工作室",
     "early_actions": "研究解剖、光学、飞行器设计",
     "breakthrough": "《最后的晚餐》《蒙娜丽莎》",
     "key_lesson": "艺术需要科学基础"},
    {"name": "Nicola Tesla", "name_cn": "特斯拉", "era": "工业革命", "type": "发明家",
     "vector": [0.85, 0.75, 0.5, 0.6, 0.4, 0.65, 0.85, 0.9, 0.7, 0.5, 0.8, 0.7],
     "early_career": "工程师，研究电磁学",
     "early_actions": "发明交流电机、特斯拉线圈",
     "breakthrough": "现代电力系统奠基人",
     "key_lesson": "想象未来而不是回忆过去"},
    {"name": "Confucius", "name_cn": "孔子", "era": "古代", "type": "哲学家",
     "vector": [0.7, 0.9, 0.5, 0.9, 0.3, 0.8, 0.4, 0.85, 0.9, 0.95, 0.6, 0.85],
     "early_career": "周朝史官，后成为教育家",
     "early_actions": "周游列国传播儒家思想",
     "breakthrough": "《论语》影响东亚两千年",
     "key_lesson": "有教无类，因材施教"},
    {"name": "Aristotle", "name_cn": "亚里士多德", "era": "古代", "type": "哲学家",
     "vector": [0.85, 0.8, 0.6, 0.7, 0.3, 0.7, 0.6, 0.95, 0.75, 0.7, 0.75, 0.8],
     "early_career": "柏拉图学生，亚历山大导师",
     "early_actions": "建立逻辑学、生物学、物理学体系",
     "breakthrough": "西方哲学奠基人",
     "key_lesson": "吾爱吾师，吾更爱真理"},
    {"name": "Socrates", "name_cn": "苏格拉底", "era": "古代", "type": "哲学家",
     "vector": [0.8, 0.7, 0.6, 0.75, 0.4, 0.65, 0.5, 0.9, 0.7, 0.8, 0.65, 0.75],
     "early_career": "雅典街头辩论者",
     "early_actions": "开创问答式教学法",
     "breakthrough": "认识你自己",
     "key_lesson": "未经审视的人生不值得过"},
    {"name": "Plato", "name_cn": "柏拉图", "era": "古代", "type": "哲学家",
     "vector": [0.9, 0.75, 0.5, 0.65, 0.3, 0.7, 0.55, 0.9, 0.7, 0.65, 0.8, 0.7],
     "early_career": "苏格拉底学生，创立学园",
     "early_actions": "写作《理想国》《会饮篇》",
     "breakthrough": "理念论影响整个西方哲学",
     "key_lesson": "知识即回忆"},
    {"name": "Aristophanes", "name_cn": "阿里斯托芬", "era": "古代", "type": "作家",
     "vector": [0.85, 0.6, 0.8, 0.6, 0.5, 0.55, 0.7, 0.75, 0.55, 0.65, 0.6, 0.5],
     "early_career": "喜剧作家，雅典剧场",
     "early_actions": "创作《云》《蛙》等喜剧",
     "breakthrough": "旧喜剧代表人物",
     "key_lesson": "幽默是智慧的表达"},
    {"name": "Homer", "name_cn": "荷马", "era": "古代", "type": "诗人",
     "vector": [0.9, 0.65, 0.5, 0.7, 0.4, 0.5, 0.6, 0.8, 0.6, 0.75, 0.55, 0.6],
     "early_career": "盲诗人，游吟歌手",
     "early_actions": "传唱《伊利亚特》《奥德赛》",
     "breakthrough": "西方文学奠基人",
     "key_lesson": "故事永恒流传"},
    {"name": "Virgil", "name_cn": "维吉尔", "era": "古代", "type": "诗人",
     "vector": [0.8, 0.7, 0.5, 0.65, 0.35, 0.55, 0.55, 0.85, 0.65, 0.7, 0.6, 0.65],
     "early_career": "罗马诗人，受奥古斯都庇护",
     "early_actions": "写作《埃涅阿斯纪》",
     "breakthrough": "罗马民族史诗",
     "key_lesson": "使命高于个人"},
    {"name": "Cicero", "name_cn": "西塞罗", "era": "古代", "type": "政治家",
     "vector": [0.75, 0.8, 0.7, 0.6, 0.4, 0.85, 0.5, 0.9, 0.7, 0.55, 0.7, 0.75],
     "early_career": "律师出身，后从政",
     "early_actions": "演说反对喀提林阴谋",
     "breakthrough": "罗马修辞学大师",
     "key_lesson": "语言是权力的工具"},
    {"name": "Julius Caesar", "name_cn": "凯撒", "era": "古代", "type": "政治家",
     "vector": [0.7, 0.75, 0.8, 0.5, 0.5, 0.95, 0.85, 0.7, 0.7, 0.4, 0.9, 0.8],
     "early_career": "军队崛起，征服高卢",
     "early_actions": "跨越卢比孔河，独裁罗马",
     "breakthrough": "凯撒历法沿用至今",
     "key_lesson": "我来，我见，我征服"},
    {"name": "Alexander the Great", "name_cn": "亚历山大大帝", "era": "古代", "type": "征服者",
     "vector": [0.75, 0.7, 0.85, 0.55, 0.45, 0.95, 0.9, 0.65, 0.65, 0.45, 0.95, 0.85],
     "early_career": "师从亚里士多德",
     "early_actions": "东征波斯，建立庞大帝国",
     "breakthrough": "希腊化时代开创者",
     "key_lesson": "世界是我的祖国"},
    {"name": "Cleopatra", "name_cn": "克娄巴特拉", "era": "古代", "type": "统治者",
     "vector": [0.8, 0.75, 0.7, 0.6, 0.5, 0.9, 0.75, 0.7, 0.7, 0.65, 0.85, 0.75],
     "early_career": "埃及女王，精通多国语言",
     "early_actions": "与凯撒、安东尼结盟",
     "breakthrough": "最后一位法老",
     "key_lesson": "智慧胜于武力"},
    {"name": "Augustus Caesar", "name_cn": "奥古斯都", "era": "古代", "type": "统治者",
     "vector": [0.65, 0.85, 0.6, 0.55, 0.35, 0.9, 0.6, 0.75, 0.8, 0.5, 0.8, 0.85],
     "early_career": "凯撒养子，内战胜利",
     "early_actions": "建立元首制，开创罗马和平",
     "breakthrough": "罗马帝国奠基人",
     "key_lesson": "找到纸屋留下大理石"},
    {"name": "Trajan", "name_cn": "图拉真", "era": "古代", "type": "统治者",
     "vector": [0.7, 0.8, 0.65, 0.6, 0.3, 0.85, 0.7, 0.7, 0.75, 0.55, 0.75, 0.8],
     "early_career": "军团将领，后成为皇帝",
     "early_actions": "扩张帝国版图至最大",
     "breakthrough": "图拉真柱纪念功绩",
     "key_lesson": "最好的君主是公民第一"},
    {"name": "Marcus Aurelius", "name_cn": "马可·奥勒留", "era": "古代", "type": "哲学家",
     "vector": [0.8, 0.85, 0.5, 0.75, 0.3, 0.7, 0.45, 0.85, 0.85, 0.8, 0.65, 0.8],
     "early_career": "斯多葛学派学生，后成为皇帝",
     "early_actions": "写作《沉思录》",
     "breakthrough": "哲人王典范",
     "key_lesson": "控制你能控制的"},
    {"name": "Hadrian", "name_cn": "哈德良", "era": "古代", "type": "统治者",
     "vector": [0.85, 0.8, 0.55, 0.6, 0.35, 0.75, 0.65, 0.8, 0.7, 0.55, 0.7, 0.75],
     "early_career": "军人出身，热爱希腊文化",
     "early_actions": "修建哈德良长城",
     "breakthrough": "罗马黄金时代统治者",
     "key_lesson": "建设比征服更难"},
    {"name": "Constantine", "name_cn": "君士坦丁", "era": "古代", "type": "统治者",
     "vector": [0.7, 0.75, 0.7, 0.55, 0.4, 0.9, 0.7, 0.65, 0.7, 0.5, 0.8, 0.75],
     "early_career": "军团将领，统一帝国",
     "early_actions": "颁布米兰敕令",
     "breakthrough": "基督教合法化",
     "key_lesson": "信仰统一帝国"},
    {"name": "Charlemagne", "name_cn": "查理曼", "era": "中世纪", "type": "统治者",
     "vector": [0.65, 0.8, 0.65, 0.55, 0.35, 0.9, 0.75, 0.6, 0.75, 0.45, 0.8, 0.8],
     "early_career": "法兰克国王，统一西欧",
     "early_actions": "建立加洛林帝国",
     "breakthrough": "欧洲之父",
     "key_lesson": "知识照亮权力"},
    {"name": "Leonardo Fibonacci", "name_cn": "斐波那契", "era": "中世纪", "type": "数学家",
     "vector": [0.9, 0.75, 0.4, 0.6, 0.3, 0.55, 0.65, 0.9, 0.7, 0.5, 0.6, 0.7],
     "early_career": "商人家庭，北非学习数学",
     "early_actions": "引入印度-阿拉伯数字",
     "breakthrough": "斐波那契数列",
     "key_lesson": "数学是宇宙的语言"},
    {"name": "Thomas Aquinas", "name_cn": "阿奎那", "era": "中世纪", "type": "神学家",
     "vector": [0.85, 0.8, 0.4, 0.65, 0.3, 0.6, 0.45, 0.9, 0.8, 0.6, 0.65, 0.75],
     "early_career": "修道院学习，后成为神学家",
     "early_actions": "写作《神学大全》",
     "breakthrough": "经院哲学集大成者",
     "key_lesson": "信仰与理性和谐"},
    {"name": "Dante Alighieri", "name_cn": "但丁", "era": "文艺复兴", "type": "诗人",
     "vector": [0.9, 0.75, 0.5, 0.6, 0.4, 0.65, 0.55, 0.85, 0.7, 0.65, 0.7, 0.65],
     "early_career": "佛罗伦萨诗人，后流放",
     "early_actions": "写作《神曲》",
     "breakthrough": "意大利语文学奠基人",
     "key_lesson": "跟随你的星"},
    {"name": "Petrarch", "name_cn": "彼特拉克", "era": "文艺复兴", "type": "诗人",
     "vector": [0.9, 0.7, 0.55, 0.65, 0.35, 0.6, 0.5, 0.85, 0.65, 0.7, 0.65, 0.7],
     "early_career": "学者，收集古典手稿",
     "early_actions": "创作十四行诗",
     "breakthrough": "人文主义之父",
     "key_lesson": "回归古典智慧"},
    {"name": "Boccaccio", "name_cn": "薄伽丘", "era": "文艺复兴", "type": "作家",
     "vector": [0.85, 0.65, 0.6, 0.7, 0.4, 0.55, 0.6, 0.8, 0.6, 0.75, 0.6, 0.65],
     "early_career": "商人子弟，后成为作家",
     "early_actions": "写作《十日谈》",
     "breakthrough": "短篇小说奠基人",
     "key_lesson": "人性是永恒的题材"},
    {"name": "Machiavelli", "name_cn": "马基雅维利", "era": "文艺复兴", "type": "政治家",
     "vector": [0.75, 0.7, 0.6, 0.45, 0.5, 0.85, 0.7, 0.8, 0.65, 0.4, 0.7, 0.6],
     "early_career": "佛罗伦萨外交官",
     "early_actions": "写作《君主论》",
     "breakthrough": "现代政治学奠基人",
     "key_lesson": "目的证明手段正当"},
    {"name": "Copernicus", "name_cn": "哥白尼", "era": "文艺复兴", "type": "科学家",
     "vector": [0.85, 0.8, 0.4, 0.55, 0.3, 0.6, 0.65, 0.9, 0.75, 0.5, 0.7, 0.8],
     "early_career": "教士，研究天文学",
     "early_actions": "提出日心说",
     "breakthrough": "《天体运行论》",
     "key_lesson": "真理需要勇气"},
    {"name": "Tycho Brahe", "name_cn": "第谷", "era": "文艺复兴", "type": "科学家",
     "vector": [0.8, 0.85, 0.5, 0.6, 0.35, 0.65, 0.6, 0.85, 0.8, 0.55, 0.65, 0.75],
     "early_career": "丹麦贵族，建造天文台",
     "early_actions": "精确观测行星运动",
     "breakthrough": "第谷体系",
     "key_lesson": "细节决定科学"},
    {"name": "Kepler", "name_cn": "开普勒", "era": "文艺复兴", "type": "科学家",
     "vector": [0.9, 0.8, 0.45, 0.55, 0.3, 0.6, 0.65, 0.9, 0.75, 0.5, 0.7, 0.8],
     "early_career": "牧师之子，研究数学",
     "early_actions": "发现行星运动三定律",
     "breakthrough": "《新天文学》",
     "key_lesson": "宇宙遵循数学定律"},
    {"name": "Bruno", "name_cn": "布鲁诺", "era": "文艺复兴", "type": "哲学家",
     "vector": [0.95, 0.65, 0.55, 0.6, 0.5, 0.7, 0.8, 0.8, 0.6, 0.65, 0.85, 0.7],
     "early_career": "修道士，后成为哲学家",
     "early_actions": "支持日心说，提出无限宇宙",
     "breakthrough": "为科学自由殉道",
     "key_lesson": "思想不能被束缚"},
    {"name": "Francis Bacon", "name_cn": "培根", "era": "文艺复兴", "type": "哲学家",
     "vector": [0.85, 0.8, 0.6, 0.65, 0.35, 0.7, 0.65, 0.85, 0.75, 0.6, 0.7, 0.75],
     "early_career": "律师，后成为哲学家",
     "early_actions": "提出归纳法",
     "breakthrough": "《新工具》",
     "key_lesson": "知识就是力量"},
    {"name": "Descartes", "name_cn": "笛卡尔", "era": "近代", "type": "哲学家",
     "vector": [0.9, 0.75, 0.5, 0.6, 0.4, 0.65, 0.7, 0.95, 0.7, 0.55, 0.7, 0.7],
     "early_career": "贵族，研究数学哲学",
     "early_actions": "创立解析几何",
     "breakthrough": "我思故我在",
     "key_lesson": "怀疑一切"},
    {"name": "Pascal", "name_cn": "帕斯卡", "era": "近代", "type": "科学家",
     "vector": [0.85, 0.8, 0.5, 0.65, 0.35, 0.6, 0.65, 0.9, 0.75, 0.6, 0.65, 0.75],
     "early_career": "神童，研究数学物理",
     "early_actions": "发明计算器，研究概率",
     "breakthrough": "《思想录》",
     "key_lesson": "心灵有理性不知晓的理由"},
    {"name": "Newton", "name_cn": "牛顿", "era": "近代", "type": "科学家",
     "vector": [0.8, 0.95, 0.4, 0.5, 0.3, 0.7, 0.6, 0.95, 0.9, 0.4, 0.8, 0.9],
     "early_career": "剑桥研究微积分光学",
     "early_actions": "发现万有引力，建立力学",
     "breakthrough": "《自然哲学的数学原理》",
     "key_lesson": "站在巨人肩膀上"},
    {"name": "Leibniz", "name_cn": "莱布尼茨", "era": "近代", "type": "科学家",
     "vector": [0.9, 0.8, 0.55, 0.65, 0.35, 0.65, 0.6, 0.9, 0.75, 0.6, 0.7, 0.75],
     "early_career": "律师，研究数学哲学",
     "early_actions": "独立发明微积分",
     "breakthrough": "二进制原理",
     "key_lesson": "宇宙是最佳可能世界"},
    {"name": "Huygens", "name_cn": "惠更斯", "era": "近代", "type": "科学家",
     "vector": [0.85, 0.8, 0.5, 0.6, 0.35, 0.6, 0.7, 0.85, 0.75, 0.55, 0.65, 0.75],
     "early_career": "贵族，研究光学力学",
     "early_actions": "发明摆钟，发现土星环",
     "breakthrough": "波动光学奠基人",
     "key_lesson": "观察创造科学"},
    {"name": "Hooke", "name_cn": "胡克", "era": "近代", "type": "科学家",
     "vector": [0.8, 0.75, 0.55, 0.6, 0.4, 0.6, 0.65, 0.8, 0.7, 0.55, 0.6, 0.7],
     "early_career": "皇家学会实验负责人",
     "early_actions": "发现胡克定律，观察细胞",
     "breakthrough": "《显微图谱》",
     "key_lesson": "细节揭示真理"},
    {"name": "Bernoulli", "name_cn": "伯努利", "era": "近代", "type": "科学家",
     "vector": [0.85, 0.8, 0.5, 0.6, 0.35, 0.65, 0.65, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "数学家家族，研究流体力学",
     "early_actions": "发现伯努利原理",
     "breakthrough": "概率论奠基",
     "key_lesson": "数学描述自然"},
    {"name": "Euler", "name_cn": "欧拉", "era": "近代", "type": "科学家",
     "vector": [0.9, 0.85, 0.45, 0.55, 0.3, 0.6, 0.6, 0.95, 0.8, 0.5, 0.65, 0.8],
     "early_career": "巴塞尔神童，后去圣彼得堡",
     "early_actions": "建立分析学，图论，拓扑",
     "breakthrough": "最多产的数学家",
     "key_lesson": "读读欧拉，读读欧拉"},
    {"name": "Lagrange", "name_cn": "拉格朗日", "era": "近代", "type": "科学家",
     "vector": [0.85, 0.8, 0.5, 0.6, 0.35, 0.65, 0.6, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "都灵学者，后去柏林",
     "early_actions": "创立分析力学",
     "breakthrough": "《分析力学》",
     "key_lesson": "纯粹分析的力量"},
    {"name": "Laplace", "name_cn": "拉普拉斯", "era": "近代", "type": "科学家",
     "vector": [0.85, 0.8, 0.5, 0.55, 0.35, 0.65, 0.65, 0.9, 0.7, 0.5, 0.7, 0.75],
     "early_career": "神学院学生，转向数学",
     "early_actions": "研究天体力学，提出星云说",
     "breakthrough": "《天体力学》",
     "key_lesson": "确定性的宇宙"},
    {"name": "Fourier", "name_cn": "傅里叶", "era": "近代", "type": "科学家",
     "vector": [0.9, 0.75, 0.5, 0.6, 0.35, 0.6, 0.7, 0.85, 0.7, 0.55, 0.65, 0.7],
     "early_career": "神职人员，后研究数学物理",
     "early_actions": "提出傅里叶分析",
     "breakthrough": "《热的解析理论》",
     "key_lesson": "任何函数都可展开"},
    {"name": "Gauss", "name_cn": "高斯", "era": "近代", "type": "科学家",
     "vector": [0.9, 0.85, 0.45, 0.55, 0.3, 0.6, 0.6, 0.95, 0.8, 0.5, 0.7, 0.8],
     "early_career": "神童，哥廷根教授",
     "early_actions": "数论、代数、几何、分析全才",
     "breakthrough": "《算术研究》",
     "key_lesson": "数学是科学之王"},
    {"name": "Bolzano", "name_cn": "波尔扎诺", "era": "近代", "type": "科学家",
     "vector": [0.85, 0.8, 0.5, 0.65, 0.35, 0.6, 0.55, 0.85, 0.75, 0.6, 0.65, 0.75],
     "early_career": "神职人员，研究数学逻辑",
     "early_actions": "分析严格化先驱",
     "breakthrough": "悖论研究",
     "key_lesson": "逻辑需要精确"},
    {"name": "Riemann", "name_cn": "黎曼", "type": "科学家", "era": "近代",
     "vector": [0.95, 0.75, 0.4, 0.55, 0.3, 0.55, 0.65, 0.95, 0.7, 0.5, 0.65, 0.75],
     "early_career": "哥廷根学者，研究几何",
     "early_actions": "创立黎曼几何",
     "breakthrough": "《论几何基础的假设》",
     "key_lesson": "空间可以是弯曲的"},
    {"name": "Hamilton", "name_cn": "哈密顿", "era": "近代", "type": "科学家",
     "vector": [0.9, 0.8, 0.5, 0.6, 0.35, 0.65, 0.6, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "都柏林学者，研究力学",
     "early_actions": "发明四元数",
     "breakthrough": "分析动力学",
     "key_lesson": "数学发现而非发明"},
    {"name": "Boole", "name_cn": "布尔", "era": "近代", "type": "科学家",
     "vector": [0.85, 0.8, 0.5, 0.6, 0.35, 0.6, 0.55, 0.85, 0.7, 0.55, 0.65, 0.7],
     "early_career": "自学成才，研究逻辑",
     "early_actions": "创立布尔代数",
     "breakthrough": "《思维的规律》",
     "key_lesson": "逻辑可计算"},
    {"name": "Cantor", "name_cn": "康托尔", "era": "近代", "type": "科学家",
     "vector": [0.95, 0.75, 0.45, 0.55, 0.4, 0.6, 0.6, 0.9, 0.7, 0.5, 0.7, 0.75],
     "early_career": "哥廷根学者，研究数论",
     "early_actions": "创立集合论",
     "breakthrough": "无穷有不同的等级",
     "key_lesson": "我的理论的时代终于来临"},
    {"name": "Poincare", "name_cn": "庞加莱", "era": "近代", "type": "科学家",
     "vector": [0.9, 0.8, 0.55, 0.6, 0.35, 0.65, 0.65, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "工程师，后成为数学家",
     "early_actions": "拓扑学奠基，混沌理论先驱",
     "breakthrough": "《科学与假设》",
     "key_lesson": "直觉是数学发现的钥匙"},
    {"name": "Hilbert", "name_cn": "希尔伯特", "era": "近代", "type": "科学家",
     "vector": [0.9, 0.85, 0.5, 0.6, 0.35, 0.7, 0.6, 0.9, 0.8, 0.55, 0.75, 0.8],
     "early_career": "哥廷根学派领袖",
     "early_actions": "提出23个问题",
     "breakthrough": "公理化方法",
     "key_lesson": "我们必须知道，我们必将知道"},
    {"name": "Noether", "name_cn": "诺特", "era": "现代", "type": "科学家",
     "vector": [0.95, 0.85, 0.45, 0.65, 0.3, 0.6, 0.55, 0.95, 0.8, 0.6, 0.7, 0.75],
     "early_career": "哥廷根学者，研究代数",
     "early_actions": "创立抽象代数，诺特定理",
     "breakthrough": "爱因斯坦称她改变物理学",
     "key_lesson": "对称决定守恒"},
    {"name": "Godel", "name_cn": "哥德尔", "era": "现代", "type": "科学家",
     "vector": [0.95, 0.8, 0.4, 0.55, 0.4, 0.6, 0.5, 0.95, 0.75, 0.5, 0.65, 0.7],
     "early_career": "维也纳学者，研究逻辑",
     "early_actions": "证明不完备定理",
     "breakthrough": "改变数学基础",
     "key_lesson": "系统不能证明自身一致性"},
    {"name": "Turing", "name_cn": "图灵", "era": "现代", "type": "科学家",
     "vector": [0.9, 0.8, 0.5, 0.6, 0.35, 0.65, 0.7, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "剑桥学者，研究逻辑",
     "early_actions": "提出图灵机，破解恩尼格玛",
     "breakthrough": "人工智能之父",
     "key_lesson": "机器能思考吗？"},
    {"name": "Von Neumann", "name_cn": "冯·诺依曼", "era": "现代", "type": "科学家",
     "vector": [0.9, 0.85, 0.55, 0.6, 0.35, 0.7, 0.7, 0.95, 0.8, 0.55, 0.75, 0.8],
     "early_career": "布达佩斯神童，后去美国",
     "early_actions": "量子力学、博弈论、计算机",
     "breakthrough": "存储程序计算机",
     "key_lesson": "数学无处不在"},
    {"name": "Turing", "name_cn": "阿兰·图灵", "era": "现代", "type": "科学家",
     "vector": [0.9, 0.8, 0.5, 0.6, 0.35, 0.65, 0.7, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "剑桥学者，二战密码破译",
     "early_actions": "提出图灵机模型",
     "breakthrough": "图灵测试定义人工智能",
     "key_lesson": "机器能思考吗"},
    {"name": "Shannon", "name_cn": "香农", "era": "现代", "type": "科学家",
     "vector": [0.85, 0.8, 0.5, 0.6, 0.35, 0.65, 0.65, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "MIT学者，研究开关电路",
     "early_actions": "创立信息论",
     "breakthrough": "《通信的数学理论》",
     "key_lesson": "信息是可量化的"},
    {"name": "Wiener", "name_cn": "维纳", "era": "现代", "type": "科学家",
     "vector": [0.9, 0.8, 0.45, 0.6, 0.35, 0.65, 0.6, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "神童，研究控制论",
     "early_actions": "创立控制论",
     "breakthrough": "《控制论》",
     "key_lesson": "反馈决定行为"},
    {"name": "Turing Award", "name_cn": "图灵奖", "era": "现代", "type": "奖项",
     "vector": [0.9, 0.8, 0.5, 0.6, 0.35, 0.65, 0.7, 0.9, 0.75, 0.55, 0.7, 0.75],
     "early_career": "计算机科学最高荣誉",
     "early_actions": "奖励杰出贡献",
     "breakthrough": "计算机领域的诺贝尔奖",
     "key_lesson": "纪念图灵的贡献"},
]

# Replace placeholders
for i, (idx, placeholder) in enumerate(placeholders):
    if i < len(MORE_FIGURES):
        real = MORE_FIGURES[i]
        figures[idx]["name"] = real["name"]
        figures[idx]["name_cn"] = real["name_cn"]
        figures[idx]["era"] = real["era"]
        figures[idx]["type"] = real["type"]
        figures[idx]["vector"] = real["vector"]
        figures[idx]["early_career"] = real["early_career"]
        figures[idx]["early_actions"] = real["early_actions"]
        figures[idx]["breakthrough"] = real["breakthrough"]
        figures[idx]["key_lesson"] = real["key_lesson"]
        print(f"  {i+1}. {real['name_cn']} ({real['name']})")

# Save
data["figures"] = figures
with open(figs_file, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"\n✓ Updated {len(placeholders)} figures")
print(f"✓ Saved to {figs_file}")
