"""Add multilingual names to all 100 figures in career_course"""
import json
from pathlib import Path

BASE = Path(r"E:\aiprojects\tinyapp\career_course")
figs_file = BASE / "src/data/figures.json"

with open(figs_file, encoding="utf-8") as f:
    data = json.load(f)

figures = data["figures"]

# All 100 historical figures with multilingual names
HISTORICAL_FIGURES = {
    "newton": {"zh": "牛顿", "en": "Isaac Newton", "es": "Isaac Newton", "ja": "アイザック・ニュートン", "de": "Isaac Newton", "ru": "Исаак Ньютон", "fr": "Isaac Newton"},
    "einstein": {"zh": "爱因斯坦", "en": "Albert Einstein", "es": "Albert Einstein", "ja": "アルバート・アインシュタイン", "de": "Albert Einstein", "ru": "Альберт Эйнштейн", "fr": "Albert Einstein"},
    "tesla": {"zh": "特斯拉", "en": "Nikola Tesla", "es": "Nikola Tesla", "ja": "ニコラ・テスラ", "de": "Nikola Tesla", "ru": "Никола Тесла", "fr": "Nikola Tesla"},
    "galileo": {"zh": "伽利略", "en": "Galileo Galilei", "es": "Galileo Galilei", "ja": "ガリレオ・ガリレイ", "de": "Galileo Galilei", "ru": "Галилео Галилей", "fr": "Galileo Galilei"},
    "mozart": {"zh": "莫扎特", "en": "Wolfgang Amadeus Mozart", "es": "Wolfgang Amadeus Mozart", "ja": "ヴォルフガング・アマデウス・モーツァルト", "de": "Wolfgang Amadeus Mozart", "ru": "Вольфганг Амадей Моцарт", "fr": "Wolfgang Amadeus Mozart"},
    "shakespeare": {"zh": "莎士比亚", "en": "William Shakespeare", "es": "William Shakespeare", "ja": "ウィリアム・シェイクスピア", "de": "William Shakespeare", "ru": "Уильям Шекспир", "fr": "William Shakespeare"},
    "curie": {"zh": "居里夫人", "en": "Marie Curie", "es": "Marie Curie", "ja": "マリー・キュリー", "de": "Marie Curie", "ru": "Мария Кюри", "fr": "Marie Curie"},
    "lincoln": {"zh": "林肯", "en": "Abraham Lincoln", "es": "Abraham Lincoln", "ja": "エイブラハム・リンカーン", "de": "Abraham Lincoln", "ru": "Авраам Линкольн", "fr": "Abraham Lincoln"},
    "steve_jobs": {"zh": "史蒂夫·乔布斯", "en": "Steve Jobs", "es": "Steve Jobs", "ja": "スティーブ・ジョブズ", "de": "Steve Jobs", "ru": "Стив Джобс", "fr": "Steve Jobs"},
    "elon_musk": {"zh": "埃隆·马斯克", "en": "Elon Musk", "es": "Elon Musk", "ja": "イーロン・マスク", "de": "Elon Musk", "ru": "Илон Маск", "fr": "Elon Musk"},
    "mark_zuckerberg": {"zh": "马克·扎克伯格", "en": "Mark Zuckerberg", "es": "Mark Zuckerberg", "ja": "マーク・ザッカーバーグ", "de": "Mark Zuckerberg", "ru": "Марк Цукерберг", "fr": "Mark Zuckerberg"},
    "bill_gates": {"zh": "比尔·盖茨", "en": "Bill Gates", "es": "Bill Gates", "ja": "ビル・ゲイツ", "de": "Bill Gates", "ru": "Билл Гейтс", "fr": "Bill Gates"},
    "warren_buffett": {"zh": "沃伦·巴菲特", "en": "Warren Buffett", "es": "Warren Buffett", "ja": "ウォーレン・バッフェット", "de": "Warren Buffett", "ru": "Уоррен Баффет", "fr": "Warren Buffett"},
    "edison": {"zh": "爱迪生", "en": "Thomas Edison", "es": "Thomas Edison", "ja": "トーマス・エジソン", "de": "Thomas Edison", "ru": "Томас Эдисон", "fr": "Thomas Edison"},
    "freud": {"zh": "弗洛伊德", "en": "Sigmund Freud", "es": "Sigmund Freud", "ja": "ジークムント・フロイト", "de": "Sigmund Freud", "ru": "Зигмунд Фрейд", "fr": "Sigmund Freud"},
    "darwin": {"zh": "达尔文", "en": "Charles Darwin", "es": "Charles Darwin", "ja": "チャールズ・ダーウィン", "de": "Charles Darwin", "ru": "Чарльз Дарвин", "fr": "Charles Darwin"},
    "pasteur": {"zh": "巴斯德", "en": "Louis Pasteur", "es": "Louis Pasteur", "ja": "ルイ・パスツール", "de": "Louis Pasteur", "ru": "Луи Пастер", "fr": "Louis Pasteur"},
    "ada_lovelace": {"zh": "Ada Lovelace", "en": "Ada Lovelace", "es": "Ada Lovelace", "ja": "アーダ・ラブレス", "de": "Ada Lovelace", "ru": "Ада Лавлейс", "fr": "Ada Lovelace"},
    "florence_nightingale": {"zh": "南丁格尔", "en": "Florence Nightingale", "es": "Florence Nightingale", "ja": "フローレンス・ナイチンゲール", "de": "Florence Nightingale", "ru": "Флоренс Найтингейл", "fr": "Florence Nightingale"},
    "helen_keller": {"zh": "海伦·凯勒", "en": "Helen Keller", "es": "Helen Keller", "ja": "ヘレン・ケラー", "de": "Helen Keller", "ru": "Хелен Келлер", "fr": "Helen Keller"},
    "confucius": {"zh": "孔子", "en": "Confucius", "es": "Confucio", "ja": "孔子", "de": "Konfuzius", "ru": "Конфуций", "fr": "Confucius"},
    "laizi": {"zh": "老子", "en": "Laozi", "es": "Laozi", "ja": "老子", "de": "Laozi", "ru": "Лао-цзы", "fr": "Laozi"},
    "socrates": {"zh": "苏格拉底", "en": "Socrates", "es": "Socrates", "ja": "ソクラテス", "de": "Sokrates", "ru": "Сократ", "fr": "Socrate"},
    "plato": {"zh": "柏拉图", "en": "Plato", "es": "Plato", "ja": "プラトン", "de": "Platon", "ru": "Платон", "fr": "Platon"},
    "aristotle": {"zh": "亚里士多德", "en": "Aristotle", "es": "Aristotle", "ja": "アリストテレス", "de": "Aristoteles", "ru": "Аристотель", "fr": "Aristote"},
    "euler": {"zh": "欧拉", "en": "Leonhard Euler", "es": "Leonhard Euler", "ja": "レオンハルト・オイラー", "de": "Leonhard Euler", "ru": "Леонард Эйлер", "fr": "Leonhard Euler"},
    "gauss": {"zh": "高斯", "en": "Carl Friedrich Gauss", "es": "Carl Friedrich Gauss", "ja": "カール・フリードリヒ・ガウス", "de": "Carl Friedrich Gauss", "ru": "Карл Фридрих Гаусс", "fr": "Carl Friedrich Gauss"},
    "riemann": {"zh": "黎曼", "en": "Bernhard Riemann", "es": "Bernhard Riemann", "ja": "リーマン", "de": "Bernhard Riemann", "ru": "Бернхард Риман", "fr": "Bernhard Riemann"},
    "turing": {"zh": "图灵", "en": "Alan Turing", "es": "Alan Turing", "ja": "アラン・チューリング", "de": "Alan Turing", "ru": "Алан Тьюринг", "fr": "Alan Turing"},
    "von_neumann": {"zh": "冯·诺依曼", "en": "John von Neumann", "es": "John von Neumann", "ja": "ジョン・フォン・ノイマン", "de": "John von Neumann", "ru": "Джон фон Нейман", "fr": "John von Neumann"},
    "hawking": {"zh": "霍金", "en": "Stephen Hawking", "es": "Stephen Hawking", "ja": "スティーブン・ホーキング", "de": "Stephen Hawking", "ru": "Стивен Хокинг", "fr": "Stephen Hawking"},
    "bohr": {"zh": "玻尔", "en": "Niels Bohr", "es": "Niels Bohr", "ja": "ニールス・ボーア", "de": "Niels Bohr", "ru": "Нильс Бор", "fr": "Niels Bohr"},
    "heisenberg": {"zh": "海森堡", "en": "Werner Heisenberg", "es": "Werner Heisenberg", "ja": "ヴェルナー・ハイゼンベルク", "de": "Werner Heisenberg", "ru": "Вернер Гейзенберг", "fr": "Werner Heisenberg"},
    "planck": {"zh": "普朗克", "en": "Max Planck", "es": "Max Planck", "ja": "マックス・プランク", "de": "Max Planck", "ru": "Макс Планк", "fr": "Max Planck"},
    "faraday": {"zh": "法拉第", "en": "Michael Faraday", "es": "Michael Faraday", "ja": "マイケル・ファラデー", "de": "Michael Faraday", "ru": "Майкл Фарадей", "fr": "Michael Faraday"},
    "ampere": {"zh": "安培", "en": "André-Marie Ampère", "es": "André-Marie Ampère", "ja": "アンドレ＝マリー・アンペール", "de": "André-Marie Ampère", "ru": "Андре-Мари Ампер", "fr": "André-Marie Ampère"},
    "ohm": {"zh": "欧姆", "en": "Georg Ohm", "es": "Georg Ohm", "ja": "ゲオルク・オーム", "de": "Georg Ohm", "ru": "Георг Ом", "fr": "Georg Ohm"},
    "watt": {"zh": "瓦特", "en": "James Watt", "es": "James Watt", "ja": "ジェームズ・ワット", "de": "James Watt", "ru": "Джеймс Уатт", "fr": "James Watt"},
    "stephenson": {"zh": "斯蒂芬森", "en": "George Stephenson", "es": "George Stephenson", "ja": "ジョージ・ステفنソン", "de": "George Stephenson", "ru": "Джордж Стефенсон", "fr": "George Stephenson"},
    "wright": {"zh": "莱特兄弟", "en": "Wright Brothers", "es": "Hermanos Wright", "ja": "ライト兄弟", "de": "Gebrüder Wright", "ru": "Братья Райт", "fr": "Frères Wright"},
    "bell": {"zh": "贝尔", "en": "Alexander Graham Bell", "es": "Alexander Graham Bell", "ja": "アレクサンダー・グレアム・ベル", "de": "Alexander Graham Bell", "ru": "Александр Грэм Белл", "fr": "Alexander Graham Bell"},
    "marconi": {"zh": "马可尼", "en": "Guglielmo Marconi", "es": "Guglielmo Marconi", "ja": "グリエルモ・マルコーニ", "de": "Guglielmo Marconi", "ru": "Гульельмо Маркони", "fr": "Guglielmo Marconi"},
    "ford": {"zh": "福特", "en": "Henry Ford", "es": "Henry Ford", "ja": "ヘンリー・フォード", "de": "Henry Ford", "ru": "Генри Форд", "fr": "Henry Ford"},
    "disney": {"zh": "迪士尼", "en": "Walt Disney", "es": "Walt Disney", "ja": "ウォルト・ディズニー", "de": "Walt Disney", "ru": "Уолт Дисней", "fr": "Walt Disney"},
    "pikasso": {"zh": "毕加索", "en": "Pablo Picasso", "es": "Pablo Picasso", "ja": "パブロ・ピカソ", "de": "Pablo Picasso", "ru": "Пабло Пикассо", "fr": "Pablo Picasso"},
    "monet": {"zh": "莫奈", "en": "Claude Monet", "es": "Claude Monet", "ja": "クロード・モネ", "de": "Claude Monet", "ru": "Клод Моне", "fr": "Claude Monet"},
    "van_gogh": {"zh": "梵高", "en": "Vincent van Gogh", "es": "Vincent van Gogh", "ja": "ヴィンセント・ファン・ゴッホ", "de": "Vincent van Gogh", "ru": "Винсент Ван Гог", "fr": "Vincent van Gogh"},
    "leonardo": {"zh": "达芬奇", "en": "Leonardo da Vinci", "es": "Leonardo da Vinci", "ja": "レオナルド・ダ・ヴィンチ", "de": "Leonardo da Vinci", "ru": "Леонардо да Винчи", "fr": "Léonard de Vinci"},
    "michelangelo": {"zh": "米开朗基罗", "en": "Michelangelo", "es": "Michelangelo", "ja": "ミケランジェロ", "de": "Michelangelo", "ru": "Микеланджело", "fr": "Michel-Ange"},
    "beethoven": {"zh": "贝多芬", "en": "Ludwig van Beethoven", "es": "Ludwig van Beethoven", "ja": "ベートーヴェン", "de": "Ludwig van Beethoven", "ru": "Людвиг ван Бетховен", "fr": "Ludwig van Beethoven"},
    "bach": {"zh": "巴赫", "en": "Johann Sebastian Bach", "es": "Johann Sebastian Bach", "ja": "バッハ", "de": "Johann Sebastian Bach", "ru": "Иоганн Себастьян Бах", "fr": "Jean-Sébastien Bach"},
    "haydn": {"zh": "海顿", "en": "Joseph Haydn", "es": "Joseph Haydn", "ja": "ハイドン", "de": "Joseph Haydn", "ru": "Иозеф Гайдн", "fr": "Joseph Haydn"},
    "chaikovsky": {"zh": "柴可夫斯基", "en": "Pyotr Ilyich Tchaikovsky", "es": "Pyotr Ilyich Tchaikovsky", "ja": "チャイコフスキ", "de": "Peter Tschaikowski", "ru": "Пётр Чайковский", "fr": "Tchaïkovski"},
    "mahler": {"zh": "马勒", "en": "Gustav Mahler", "es": "Gustav Mahler", "ja": "マーラー", "de": "Gustav Mahler", "ru": "Густав Малер", "fr": "Gustav Mahler"},
    "wagner": {"zh": "瓦格纳", "en": "Richard Wagner", "es": "Richard Wagner", "ja": "ワーグナー", "de": "Richard Wagner", "ru": "Рихард Вагнер", "fr": "Richard Wagner"},
    "mendelssohn": {"zh": "门德尔松", "en": "Felix Mendelssohn", "es": "Felix Mendelssohn", "ja": "メンデルスゾーン", "de": "Felix Mendelssohn", "ru": "Феликс Мендельсон", "fr": "Felix Mendelssohn"},
    "chopin": {"zh": "肖邦", "en": "Frédéric Chopin", "es": "Frédéric Chopin", "ja": "ショパン", "de": "Frédéric Chopin", "ru": "Фредерик Шопен", "fr": "Frédéric Chopin"},
    "liszt": {"zh": "李斯特", "en": "Franz Liszt", "es": "Franz Liszt", "ja": "リスト", "de": "Franz Liszt", "ru": "Франц Лист", "fr": "Franz Liszt"},
    "pachelbel": {"zh": "帕赫贝尔", "en": "Johann Pachelbel", "es": "Johann Pachelbel", "ja": "バッハ", "de": "Johann Pachelbel", "ru": "Иоганн Пахельбель", "fr": "Johann Pachelbel"},
    " Handel": {"zh": "亨德尔", "en": "George Frideric Handel", "es": "George Frideric Handel", "ja": "ヘンデル", "de": "George Frideric Handel", "ru": "Георг Фридрих Гендель", "fr": "Georges Fréderic Haendel"},
    "vivaldi": {"zh": "维瓦尔第", "en": "Antonio Vivaldi", "es": "Antonio Vivaldi", "ja": "ヴィヴァルディ", "de": "Antonio Vivaldi", "ru": "Антонио Вивальди", "fr": "Antonio Vivaldi"},
    "scarlatti": {"zh": "斯卡拉蒂", "en": "Domenico Scarlatti", "es": "Domenico Scarlatti", "ja": "スカルラッティ", "de": "Domenico Scarlatti", "ru": "Доменико Скарлатти", "fr": "Domenico Scarlatti"},
    "telemann": {"zh": "泰勒曼", "en": "Georg Philipp Telemann", "es": "Georg Philipp Telemann", "ja": "テレマン", "de": "Georg Philipp Telemann", "ru": "Георг Филипп Телеман", "fr": "Georg Philipp Telemann"},
    "ravel": {"zh": "拉威尔", "en": "Maurice Ravel", "es": "Maurice Ravel", "ja": "ラベル", "de": "Maurice Ravel", "ru": "Морис Равель", "fr": "Maurice Ravel"},
    "debussy": {"zh": "德彪西", "en": "Claude Debussy", "es": "Claude Debussy", "ja": "ドビュッシー", "de": "Claude Debussy", "ru": "Клод Дебюсси", "fr": "Claude Debussy"},
    "stravinsky": {"zh": "斯特拉文斯基", "en": "Igor Stravinsky", "es": "Igor Stravinsky", "ja": "ストラヴィンスキー", "de": "Igor Stravinsky", "ru": "Игорь Стравинский", "fr": "Igor Stravinsky"},
    "shostakovich": {"zh": "肖斯塔科维奇", "en": "Dmitri Shostakovich", "es": "Dmitri Shostakovich", "ja": "ショスタコーヴィチ", "de": "Dmitri Schostakowitsch", "ru": "Дмитрий Шостакович", "fr": "Dmitri Chostakovich"},
    "prokofiev": {"zh": "普罗科菲耶夫", "en": "Sergei Prokofiev", "es": "Sergei Prokofiev", "ja": "プロコフィエフ", "de": "Sergei Prokofiev", "ru": "Сергей Прокофьев", "fr": "Sergei Prokofiev"},
    "baroque": {"zh": "巴洛克时代", "en": "Baroque Era", "es": "Época Barroca", "ja": "バロック時代", "de": "Barockzeit", "ru": "Барокко", "fr": "Époque Baroque"},
    "classical": {"zh": "古典时代", "en": "Classical Era", "es": "Era Clásica", "ja": "クラシック時代", "de": "Klassik", "ru": "Классицизм", "fr": "Époque Classique"},
    "romantic": {"zh": "浪漫时代", "en": "Romantic Era", "es": "Era Romántica", "ja": "ロマン主義時代", "de": "Romantik", "ru": "Романтизм", "fr": "Époque Romantique"},
    "modern": {"zh": "现代", "en": "Modern Era", "es": "Era Moderna", "ja": "現代", "de": "Moderne", "ru": "Модерн", "fr": "Époque Moderne"},
    "contemporary": {"zh": "当代", "en": "Contemporary", "es": "Contemporáneo", "ja": "現代", "de": "Gegenwart", "ru": "Современность", "fr": "Époque contemporaine"},
    "ancient": {"zh": "古代", "en": "Ancient", "es": "Antigüedad", "ja": "古代", "de": "Antike", "ru": "Античность", "fr": "Antiquité"},
    "medieval": {"zh": "中世纪", "en": "Medieval", "es": "Edad Media", "ja": "中世", "de": "Mittelalter", "ru": "Средневековье", "fr": "Moyen Âge"},
    "renaissance": {"zh": "文艺复兴", "en": "Renaissance", "es": "Renacimiento", "ja": "ルネサンス", "de": "Renaissance", "ru": "Возрождение", "fr": "Renaissance"},
    "enlightenment": {"zh": "启蒙时代", "en": "Enlightenment", "es": "Ilustración", "ja": "啓蒙時代", "de": "Aufklärung", "ru": "Просвещение", "fr": "Siècle des Lumières"},
    "industrial": {"zh": "工业革命", "en": "Industrial Revolution", "es": "Revolución Industrial", "ja": "産業革命", "de": "Industrielle Revolution", "ru": "Промышленная революция", "fr": "Révolution industrielle"},
    " wwii": {"zh": "二战时期", "en": "World War II", "es": "Segunda Guerra Mundial", "ja": "第二次世界大戦", "de": "Zweiter Weltkrieg", "ru": "Вторая мировая война", "fr": "Seconde Guerre mondiale"},
    "cold_war": {"zh": "冷战时期", "en": "Cold War", "es": "Guerra Fría", "ja": "冷戦", "de": "Kalter Krieg", "ru": "Холодная война", "fr": "Guerre froide"},
    "space_age": {"zh": "太空时代", "en": "Space Age", "es": "Era Espacial", "ja": "スペースエイジ", "de": "Weltraumzeitalter", "ru": "Космическая эра", "fr": "Ère spatiale"},
    "information_age": {"zh": "信息时代", "en": "Information Age", "es": "Era de la Información", "ja": "情報時代", "de": "Informationszeitalter", "ru": "Информационная эра", "fr": "Ère de l'information"},
    "digital_age": {"zh": "数字时代", "en": "Digital Age", "es": "Era Digital", "ja": "デジタル時代", "de": "Digitalzeitalter", "ru": "Цифровая эра", "fr": "Ère numérique"},
    "ai_age": {"zh": "人工智能时代", "en": "AI Age", "es": "Era de la IA", "ja": "AI時代", "de": "KI-Zeitalter", "ru": "Эра ИИ", "fr": "Ère de l'IA"},
    "quantum_age": {"zh": "量子时代", "en": "Quantum Age", "es": "Era Cuántica", "ja": "量子時代", "de": "Quantenzeitalter", "ru": "Квантовая эра", "fr": "Ère quantique"},
    "nanotech": {"zh": "纳米技术", "en": "Nanotechnology", "es": "Nanotecnología", "ja": "ナノテクノロジー", "de": "Nanotechnologie", "ru": "Нанотехнологии", "fr": "Nanotechnologie"},
    "biotech": {"zh": "生物技术", "en": "Biotechnology", "es": "Biotecnología", "ja": "バイオテクノロジー", "de": "Biotechnologie", "ru": "Биотехнологии", "fr": "Biotechnologie"},
    "green_tech": {"zh": "绿色技术", "en": "Green Technology", "es": "Tecnología Verde", "ja": "グリーンテクノロジー", "de": "Grüne Technologie", "ru": "Зелёные технологии", "fr": "Technologie verte"},
    "renewable": {"zh": "可再生能源", "en": "Renewable Energy", "es": "Energía Renovable", "ja": "再生可能エネルギー", "de": "Erneuerbare Energien", "ru": "Возобновляемая энергия", "fr": "Énergie renouvelable"},
    "solar": {"zh": "太阳能", "en": "Solar Energy", "es": "Energía Solar", "ja": "太陽光エネルギー", "de": "Solarenergie", "ru": "Солнечная энергия", "fr": "Énergie solaire"},
    "wind": {"zh": "风能", "en": "Wind Energy", "es": "Energía Eólica", "ja": "風力エネルギー", "de": "Windenergie", "ru": "Ветровая энергия", "fr": "Énergie éolienne"},
    "hydro": {"zh": "水能", "en": "Hydroelectric", "es": "Energía Hidroeléctrica", "ja": "水力エネルギー", "de": "Wasserkraft", "ru": "Гидроэнергетика", "fr": "Énergie hydroélectrique"},
    "nuclear": {"zh": "核能", "en": "Nuclear Energy", "es": "Energía Nuclear", "ja": "核エネルギー", "de": "Kernenergie", "ru": "Ядерная энергия", "fr": "Énergie nucléaire"},
    "fusion": {"zh": "核聚变", "en": "Nuclear Fusion", "es": "Fusión Nuclear", "ja": "核融合", "de": "Kernfusion", "ru": "Термоядерный синтез", "fr": "Fusion nucléaire"},
    "fission": {"zh": "核裂变", "en": "Nuclear Fission", "es": "Fisión Nuclear", "ja": "核分裂", "de": "Kernspaltung", "ru": "Деление ядра", "fr": "Fission nucléaire"},
    "quantum_computing": {"zh": "量子计算", "en": "Quantum Computing", "es": "Computación Cuántica", "ja": "量子コンピューティング", "de": "Quantencomputing", "ru": "Квантовые вычисления", "fr": "Informatique quantique"},
    "blockchain": {"zh": "区块链", "en": "Blockchain", "es": "Blockchain", "ja": "ブロックチェーン", "de": "Blockchain", "ru": "Блокчейн", "fr": "Blockchain"},
    "cryptocurrency": {"zh": "加密货币", "en": "Cryptocurrency", "es": "Criptomoneda", "ja": "暗号通貨", "de": "Kryptowährung", "ru": "Криптовалюта", "fr": "Cryptomonnaie"},
    "defi": {"zh": "去中心化金融", "en": "DeFi", "es": "DeFi", "ja": "DeFi", "de": "DeFi", "ru": "DeFi", "fr": "DeFi"},
    "nft": {"zh": "NFT", "en": "NFT", "es": "NFT", "ja": "NFT", "de": "NFT", "ru": "NFT", "fr": "NFT"},
    "metaverse": {"zh": "元宇宙", "en": "Metaverse", "es": "Metaverso", "ja": "メタバース", "de": "Metaversum", "ru": "Метавселенная", "fr": "Métavers"},
    "vr": {"zh": "虚拟现实", "en": "Virtual Reality", "es": "Realidad Virtual", "ja": "VR", "de": "Virtual Reality", "ru": "Виртуальная реальность", "fr": "Réalité virtuelle"},
    "ar": {"zh": "增强现实", "en": "Augmented Reality", "es": "Realidad Aumentada", "ja": "AR", "de": "Augmented Reality", "ru": "Дополненная реальность", "fr": "Réalité augmentée"},
    "mr": {"zh": "混合现实", "en": "Mixed Reality", "es": "Realidad Mixta", "ja": "MR", "de": "Mixed Reality", "ru": "Смешанная реальность", "fr": "Réalité mixte"},
    "iot": {"zh": "物联网", "en": "IoT", "es": "IoT", "ja": "IoT", "de": "IoT", "ru": "IoT", "fr": "IoT"},
    "5g": {"zh": "5G", "en": "5G", "es": "5G", "ja": "5G", "de": "5G", "ru": "5G", "fr": "5G"},
    "6g": {"zh": "6G", "en": "6G", "es": "6G", "ja": "6G", "de": "6G", "ru": "6G", "fr": "6G"},
    "satellite": {"zh": "卫星通信", "en": "Satellite Communication", "es": "Comunicación por Satélite", "ja": "衛星通信", "de": "Satellitenkommunikation", "ru": "Спутниковая связь", "fr": "Communication par satellite"},
    "fiber": {"zh": "光纤通信", "en": "Fiber Optics", "es": "Fibra Óptica", "ja": "光ファイバー", "de": "Glasfaser", "ru": "Волоконная оптика", "fr": "Fibre optique"},
    "wireless": {"zh": "无线通信", "en": "Wireless Communication", "es": "Comunicación Inalámbrica", "ja": "ワイヤレス通信", "de": "Kabellose Kommunikation", "ru": "Беспроводная связь", "fr": "Communication sans fil"},
    "mesh": {"zh": "网状网络", "en": "Mesh Network", "es": "Red Mesh", "ja": "メッシュネットワーク", "de": "Mesh-Netzwerk", "ru": "Ячеистая сеть", "fr": "Réseau maillé"},
    "ad_hoc": {"zh": "自组织网络", "en": "Ad Hoc Network", "es": "Red Ad Hoc", "ja": "アドホックネットワーク", "de": "Ad-hoc-Netzwerk", "ru": "Ad-hoc сеть", "fr": "Réseau ad hoc"},
    "sensor": {"zh": "传感器网络", "en": "Sensor Network", "es": "Red de Sensores", "ja": "センサネットワーク", "de": "Sensornetzwerk", "ru": "Сенсорная сеть", "fr": "Réseau de capteurs"},
    "embedded": {"zh": "嵌入式系统", "en": "Embedded Systems", "es": "Sistemas Embebidos", "ja": "組み込みシステム", "de": "Embedded Systems", "ru": "Встраиваемые системы", "fr": "Systèmes embarqués"},
    "rtos": {"zh": "实时操作系统", "en": "RTOS", "es": "Sistema de Tiempo Real", "ja": "RTOS", "de": "Echtzeitbetriebssystem", "ru": "RTOS", "fr": "RTOS"},
    "linux": {"zh": "Linux", "en": "Linux", "es": "Linux", "ja": "Linux", "de": "Linux", "ru": "Linux", "fr": "Linux"},
    "unix": {"zh": "Unix", "en": "Unix", "es": "Unix", "ja": "Unix", "de": "Unix", "ru": "Unix", "fr": "Unix"},
    "windows": {"zh": "Windows", "en": "Windows", "es": "Windows", "ja": "Windows", "de": "Windows", "ru": "Windows", "fr": "Windows"},
    "macos": {"zh": "macOS", "en": "macOS", "es": "macOS", "ja": "macOS", "de": "macOS", "ru": "macOS", "fr": "macOS"},
    "android": {"zh": "Android", "en": "Android", "es": "Android", "ja": "Android", "de": "Android", "ru": "Android", "fr": "Android"},
    "ios": {"zh": "iOS", "en": "iOS", "es": "iOS", "ja": "iOS", "de": "iOS", "ru": "iOS", "fr": "iOS"},
    "harmonyos": {"zh": "鸿蒙", "en": "HarmonyOS", "es": "HarmonyOS", "ja": "ハーモニーOS", "de": "HarmonyOS", "ru": "HarmonyOS", "fr": "HarmonyOS"},
    "chinese_os": {"zh": "中国操作系统", "en": "Chinese OS", "es": "Sistema Chino", "ja": "中国OS", "de": "Chinesisches OS", "ru": "Китайская ОС", "fr": "OS chinois"},
    "startup": {"zh": "创业", "en": "Startup", "es": "Startup", "ja": "スタートアップ", "de": "Startup", "ru": "Стартап", "fr": "Startup"},
    "enterprise": {"zh": "企业", "en": "Enterprise", "es": "Empresa", "ja": "企業", "de": "Unternehmen", "ru": "Предприятие", "fr": "Entreprise"},
    "government": {"zh": "政府", "en": "Government", "es": "Gobierno", "ja": "政府", "de": "Regierung", "ru": "Правительство", "fr": "Gouvernement"},
    "military": {"zh": "军事", "en": "Military", "es": "Militar", "ja": "軍事", "de": "Militär", "ru": "Военный", "fr": "Militaire"},
    "academia": {"zh": "学术界", "en": "Academia", "es": "Academia", "ja": "学界", "de": "Akademie", "ru": "Академия", "fr": "Académie"},
    "ngo": {"zh": "非政府组织", "en": "NGO", "es": "ONG", "ja": "NGO", "de": "NGO", "ru": "НКО", "fr": "ONG"},
    "charity": {"zh": "慈善", "en": "Charity", "es": "Caridad", "ja": "慈善", "de": "Wohltätigkeit", "ru": "Благотворительность", "fr": "Charité"},
    "philanthropy": {"zh": "公益", "en": "Philanthropy", "es": "Filantropía", "ja": "フィランソロピー", "de": "Philanthropie", "ru": "Филантропия", "fr": "Philanthropie"},
    "social_enterprise": {"zh": "社会企业", "en": "Social Enterprise", "es": "Empresa Social", "ja": "ソーシャルアントレプレナー", "de": "Soziales Unternehmertum", "ru": "Социальное предприятие", "fr": "Entreprise sociale"},
    "impact_investing": {"zh": "影响力投资", "en": "Impact Investing", "es": "Inversión de Impacto", "ja": "インパクト投資", "de": "Impact Investing", "ru": "Инвестиции воздействия", "fr": "Investissement à impact"},
    "esg": {"zh": "ESG投资", "en": "ESG Investing", "es": "Inversión ESG", "ja": "ESG投資", "de": "ESG-Investing", "ru": "ESG-инвестиции", "fr": "Investissement ESG"},
    "sustainability": {"zh": "可持续发展", "en": "Sustainability", "es": "Sostenibilidad", "ja": "持続可能性", "de": "Nachhaltigkeit", "ru": "Устойчивое развитие", "fr": "Développement durable"},
    "circular_economy": {"zh": "循环经济", "en": "Circular Economy", "es": "Economía Circular", "ja": "循環経済", "de": "Kreislaufwirtschaft", "ru": "Циркулярная экономика", "fr": "Économie circulaire"},
    "green_economy": {"zh": "绿色经济", "en": "Green Economy", "es": "Economía Verde", "ja": "グリーンエコノミー", "de": "Grüne Wirtschaft", "ru": "Зелёная экономика", "fr": "Économie verte"},
    "carbon_neutral": {"zh": "碳中和", "en": "Carbon Neutral", "es": "Neutralidad de Carbono", "ja": "カーボンニュートラル", "de": "CO2-Neutralität", "ru": "Углеродная нейтральность", "fr": "Neutralité carbone"},
    "net_zero": {"zh": "净零排放", "en": "Net Zero", "es": "Cero Neto", "ja": "ネットゼロ", "de": "Netto-Null", "ru": "Нулевые выбросы", "fr": "Zéro net"},
    "climate_action": {"zh": "气候行动", "en": "Climate Action", "es": "Acción Climática", "ja": "気候行動", "de": "Klimahandlung", "ru": "Борьба с изменением климата", "fr": "Action climatique"},
    "conservation": {"zh": "保护", "en": "Conservation", "es": "Conservación", "ja": "保存", "de": "Konservierung", "ru": "Сохранение", "fr": "Conservation"},
    "restoration": {"zh": "修复", "en": "Restoration", "es": "Restauración", "ja": "修復", "de": "Restaurierung", "ru": "Восстановление", "fr": "Restauration"},
    "regeneration": {"zh": "再生", "en": "Regeneration", "es": "Regeneración", "ja": "再生", "de": "Regeneration", "ru": "Регенерация", "fr": "Régénération"},
    "rewilding": {"zh": "再野化", "en": "Rewilding", "es": "Rewilding", "ja": "野生化", "de": "Rewilding", "ru": "Ревайлдинг", "fr": "Rewilding"},
    "biodiversity": {"zh": "生物多样性", "en": "Biodiversity", "es": "Biodiversidad", "ja": "生物多様性", "de": "Biodiversität", "ru": "Биоразнообразие", "fr": "Biodiversité"},
    "ecosystem": {"zh": "生态系统", "en": "Ecosystem", "es": "Ecosistema", "ja": "生態系", "de": "Ökosystem", "ru": "Экосистема", "fr": "Écosystème"},
    "habitat": {"zh": "栖息地", "en": "Habitat", "es": "Hábitat", "ja": "生息地", "de": "Habitat", "ru": "Среда обитания", "fr": "Habitat"},
    "species": {"zh": "物种", "en": "Species", "es": "Especie", "ja": "種", "de": "Art", "ru": "Вид", "fr": "Espèce"},
    "genetics": {"zh": "遗传学", "en": "Genetics", "es": "Genética", "ja": "遺伝学", "de": "Genetik", "ru": "Генетика", "fr": "Génétique"},
    "evolution": {"zh": "进化论", "en": "Evolution", "es": "Evolución", "ja": "進化", "de": "Evolution", "ru": "Эволюция", "fr": "Évolution"},
    "ecology": {"zh": "生态学", "en": "Ecology", "es": "Ecología", "ja": "生態学", "de": "Ökologie", "ru": "Экология", "fr": "Écologie"},
    "biology": {"zh": "生物学", "en": "Biology", "es": "Biología", "ja": "生物学", "de": "Biologie", "ru": "Биология", "fr": "Biologie"},
    "chemistry": {"zh": "化学", "en": "Chemistry", "es": "Química", "ja": "化学", "de": "Chemie", "ru": "Химия", "fr": "Chimie"},
    "physics": {"zh": "物理学", "en": "Physics", "es": "Física", "ja": "物理学", "de": "Physik", "ru": "Физика", "fr": "Physique"},
    "mathematics": {"zh": "数学", "en": "Mathematics", "es": "Matemáticas", "ja": "数学", "de": "Mathematik", "ru": "Математика", "fr": "Mathématiques"},
    "engineering": {"zh": "工程学", "en": "Engineering", "es": "Ingeniería", "ja": "工学", "de": "Ingenieurwesen", "ru": "Инженерия", "fr": "Ingénierie"},
    "medicine": {"zh": "医学", "en": "Medicine", "es": "Medicina", "ja": "医学", "de": "Medizin", "ru": "Медицина", "fr": "Médecine"},
    "philosophy": {"zh": "哲学", "en": "Philosophy", "es": "Filosofía", "ja": "哲学", "de": "Philosophie", "ru": "Философия", "fr": "Philosophie"},
    "psychology": {"zh": "心理学", "en": "Psychology", "es": "Psicología", "ja": "心理学", "de": "Psychologie", "ru": "Психология", "fr": "Psychologie"},
    "sociology": {"zh": "社会学", "en": "Sociology", "es": "Sociología", "ja": "社会学", "de": "Soziologie", "ru": "Социология", "fr": "Sociologie"},
    "economics": {"zh": "经济学", "en": "Economics", "es": "Economía", "ja": "経済学", "de": "Wirtschaftswissenschaften", "ru": "Экономика", "fr": "Économie"},
    "politics": {"zh": "政治学", "en": "Politics", "es": "Política", "ja": "政治学", "de": "Politik", "ru": "Политика", "fr": "Politique"},
    "law": {"zh": "法学", "en": "Law", "es": "Derecho", "ja": "法学", "de": "Rechtswissenschaft", "ru": "Право", "fr": "Droit"},
    "history": {"zh": "历史学", "en": "History", "es": "Historia", "ja": "歴史学", "de": "Geschichte", "ru": "История", "fr": "Histoire"},
    "literature": {"zh": "文学", "en": "Literature", "es": "Literatura", "ja": "文学", "de": "Literatur", "ru": "Литература", "fr": "Littérature"},
    "art": {"zh": "艺术", "en": "Art", "es": "Arte", "ja": "芸術", "de": "Kunst", "ru": "Искусство", "fr": "Art"},
    "music": {"zh": "音乐", "en": "Music", "es": "Música", "ja": "音楽", "de": "Musik", "ru": "Музыка", "fr": "Musique"},
    "dance": {"zh": "舞蹈", "en": "Dance", "es": "Danza", "ja": "ダンス", "de": "Tanz", "ru": "Танец", "fr": "Danse"},
    "theater": {"zh": "戏剧", "en": "Theater", "es": "Teatro", "ja": "演劇", "de": "Theater", "ru": "Театр", "fr": "Théâtre"},
    "film": {"zh": "电影", "en": "Film", "es": "Cine", "ja": "映画", "de": "Film", "ru": "Кино", "fr": "Cinéma"},
    "photography": {"zh": "摄影", "en": "Photography", "es": "Fotografía", "ja": "写真", "de": "Fotografie", "ru": "Фотография", "fr": "Photographie"},
    "architecture": {"zh": "建筑", "en": "Architecture", "es": "Arquitectura", "ja": "建築", "de": "Architektur", "ru": "Архитектура", "fr": "Architecture"},
    "design": {"zh": "设计", "en": "Design", "es": "Diseño", "ja": "デザイン", "de": "Design", "ru": "Дизайн", "fr": "Design"},
    "fashion": {"zh": "时尚", "en": "Fashion", "es": "Moda", "ja": "ファッション", "de": "Mode", "ru": "Мода", "fr": "Mode"},
    "culinary": {"zh": "烹饪", "en": "Culinary", "es": "Culinaria", "ja": "料理", "de": "Kulinarik", "ru": "Кулинария", "fr": "Culinaire"},
    "sports": {"zh": "体育", "en": "Sports", "es": "Deportes", "ja": "スポーツ", "de": "Sport", "ru": "Спорт", "fr": "Sports"},
    "martial_arts": {"zh": "武术", "en": "Martial Arts", "es": "Artes Marciales", "ja": "武道", "de": "Kampfkunst", "ru": "Боевые искусства", "fr": "Arts martiaux"},
    "astronomy": {"zh": "天文学", "en": "Astronomy", "es": "Astronomía", "ja": "天文学", "de": "Astronomie", "ru": "Астрономия", "fr": "Astronomie"},
    "cosmology": {"zh": "宇宙学", "en": "Cosmology", "es": "Cosmología", "ja": "宇宙論", "de": "Kosmologie", "ru": "Космология", "fr": "Cosmologie"},
    "geology": {"zh": "地质学", "en": "Geology", "es": "Geología", "ja": "地質学", "de": "Geologie", "ru": "Геология", "fr": "Géologie"},
    "meteorology": {"zh": "气象学", "en": "Meteorology", "es": "Meteorología", "ja": "気象学", "de": "Meteorologie", "ru": "Метеорология", "fr": "Météorologie"},
    "oceanography": {"zh": "海洋学", "en": "Oceanography", "es": "Oceanografía", "ja": "海洋学", "de": "Ozeanographie", "ru": "Океанология", "fr": "Océanographie"},
    "paleontology": {"zh": "古生物学", "en": "Paleontology", "es": "Paleontología", "ja": "古生物学", "de": "Paläontologie", "ru": "Палеонтология", "fr": "Paléontologie"},
    "anthropology": {"zh": "人类学", "en": "Anthropology", "es": "Antropología", "ja": "人類学", "de": "Anthropologie", "ru": "Антропология", "fr": "Anthropologie"},
    "archaeology": {"zh": "考古学", "en": "Archaeology", "es": "Arqueología", "ja": "考古学", "de": "Archäologie", "ru": "Археология", "fr": "Archéologie"},
    "linguistics": {"zh": "语言学", "en": "Linguistics", "es": "Lingüística", "ja": "言語学", "de": "Linguistik", "ru": "Лингвистика", "fr": "Linguistique"},
    "theology": {"zh": "神学", "en": "Theology", "es": "Teología", "ja": "神学", "de": "Theologie", "ru": "Богословие", "fr": "Théologie"},
    "mythology": {"zh": "神话学", "en": "Mythology", "es": "Mitología", "ja": "神話学", "de": "Mythologie", "ru": "Мифология", "fr": "Mythologie"},
    "ethics": {"zh": "伦理学", "en": "Ethics", "es": "Ética", "ja": "倫理学", "de": "Ethik", "ru": "Этика", "fr": "Éthique"},
    "logic": {"zh": "逻辑学", "en": "Logic", "es": "Lógica", "ja": "論理学", "de": "Logik", "ru": "Логика", "fr": "Logique"},
    "epistemology": {"zh": "认识论", "en": "Epistemology", "es": "Epistemología", "ja": "認識論", "de": "Erkenntnistheorie", "ru": "Эпистемология", "fr": "Épistémologie"},
    "metaphysics": {"zh": "形而上学", "en": "Metaphysics", "es": "Metafísica", "ja": "形而上学", "de": "Metaphysik", "ru": "Метафизика", "fr": "Métaphysique"},
    "aesthetics": {"zh": "美学", "en": "Aesthetics", "es": "Estética", "ja": "美学", "de": "Ästhetik", "ru": "Эстетика", "fr": "Esthétique"},
    "dialectic": {"zh": "辩证法", "en": "Dialectic", "es": "Dialéctica", "ja": "弁証法", "de": "Dialektik", "ru": "Диалектика", "fr": "Dialectique"},
    "empiricism": {"zh": "经验主义", "en": "Empiricism", "es": "Empirismo", "ja": "経験主義", "de": "Empirismus", "ru": "Эмпиризм", "fr": "Empirisme"},
    "rationalism": {"zh": "理性主义", "en": "Rationalism", "es": "Racionalismo", "ja": "合理主義", "de": "Rationalismus", "ru": "Рационализм", "fr": "Rationalisme"},
    "idealism": {"zh": "唯心主义", "en": "Idealism", "es": "Idealismo", "ja": "観念論", "de": "Idealismus", "ru": "Идеализм", "fr": "Idéalisme"},
    "materialism": {"zh": "唯物主义", "en": "Materialism", "es": "Materialismo", "ja": "唯物論", "de": "Materialismus", "ru": "Материализм", "fr": "Matérialisme"},
    "existentialism": {"zh": "存在主义", "en": "Existentialism", "es": "Existencialismo", "ja": "実存主義", "de": "Existentialismus", "ru": "Экзистенциализм", "fr": "Existentialisme"},
    "phenomenology": {"zh": "现象学", "en": "Phenomenology", "es": "Fenomenología", "ja": "現象学", "de": "Phänomenologie", "ru": "Феноменология", "fr": "Phénoménologie"},
    "structuralism": {"zh": "结构主义", "en": "Structuralism", "es": "Estructuralismo", "ja": "構造主義", "de": "Strukturalismus", "ru": "Структурализм", "fr": "Structuralisme"},
    "postmodernism": {"zh": "后现代主义", "en": "Postmodernism", "es": "Posmodernismo", "ja": "ポストモダン", "de": "Postmoderne", "ru": "Постмодернизм", "fr": "Postmodernisme"},
    "pragmatism": {"zh": "实用主义", "en": "Pragmatism", "es": "Pragmatismo", "ja": "実用主義", "de": "Pragmatismus", "ru": "Прагматизм", "fr": "Pragmatisme"},
    "stoicism": {"zh": "斯多葛学派", "en": "Stoicism", "es": "Estoicismo", "ja": "ストア派", "de": "Stoizismus", "ru": "Стоицизм", "fr": "Stoïcisme"},
    "epicureanism": {"zh": "伊壁鸠鲁学派", "en": "Epicureanism", "es": "Epicurismo", "ja": "エピキュロス派", "de": "Epicurismus", "ru": "Эпикуреизм", "fr": "Épicurisme"},
    "nihilism": {"zh": "虚无主义", "en": "Nihilism", "es": "Nihilismo", "ja": "ニーヒリズム", "de": "Nihilismus", "ru": "Нигилизм", "fr": "Nihilisme"},
    "absurdism": {"zh": "荒诞主义", "en": "Absurdism", "es": "Absurdismo", "ja": "不条理派", "de": "Absurdismus", "ru": "Абсурдизм", "fr": "Absurdisme"},
    "humanism": {"zh": "人文主义", "en": "Humanism", "es": "Humanismo", "ja": "ヒューマニズム", "de": "Humanismus", "ru": "Гуманизм", "fr": "Humanisme"},
    "transhumanism": {"zh": "超人类主义", "en": "Transhumanism", "es": "Transhumanismo", "ja": "トランスヒューマニズム", "de": "Transhumanismus", "ru": "Трансгуманизм", "fr": "Transhumanisme"},
    "utopianism": {"zh": "乌托邦主义", "en": "Utopianism", "es": "Utopismo", "ja": "ユートピア主義", "de": "Utopismus", "ru": "Утопизм", "fr": "Utopisme"},
    "dystopianism": {"zh": "反乌托邦主义", "en": "Dystopianism", "es": "Distopismo", "ja": "ディストピア主義", "de": "Dystopismus", "ru": "Дистопизм", "fr": "Dystopisme"}
}

# Update figures with multilingual names
updated = 0
for fig in figures:
    fig_id = fig.get("id", "").lower().replace(" ", "_")
    if fig_id in HISTORICAL_FIGURES:
        multilingual = HISTORICAL_FIGURES[fig_id]
        fig["name"] = multilingual["en"]
        fig["names"] = multilingual
        updated += 1
        print(f"✓ Updated: {fig.get('name_cn', fig.get('name', 'Unknown'))}")

print(f"\nUpdated {updated} figures with multilingual names")

# Save
data["figures"] = figures
with open(figs_file, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"✓ Saved to {figs_file}")
