import json
import random
from pathlib import Path

REAL = [
    {"id":"newton","name":"Isaac Newton","name_cn":"牛顿","era":"1643-1727","period":"17世纪","type":"科学家",
     "vector":{"openness":0.6,"conscientiousness":0.9,"extraversion":0.2,"agreeableness":0.2,"neuroticism":0.4,"leadership":0.5,"risk_taking":0.4,"rationality":0.95,"discipline":0.9,"empathy":0.2,"ambition":0.7,"resilience":0.8},
     "early_career":"剑桥大学三一学院学生，受疫情隔离影响深度专注数学与自然哲学。",
     "early_actions":"在隔离期间发展出微积分与运动学的核心思想。",
     "breakthrough":"发表《自然哲学的数学原理》，确立经典力学体系。",
     "key_lesson":"Standing on the shoulders of giants; 严谨与专注胜过天赋。"},
    {"id":"einstein","name":"Albert Einstein","name_cn":"爱因斯坦","era":"1879-1955","period":"20世纪","type":"科学家",
     "vector":{"openness":0.95,"conscientiousness":0.7,"extraversion":0.5,"agreeableness":0.6,"neuroticism":0.3,"leadership":0.5,"risk_taking":0.7,"rationality":0.9,"discipline":0.7,"empathy":0.6,"ambition":0.8,"resilience":0.8},
     "early_career":"瑞士专利局低级职员，业余深耕电磁理论。",
     "early_actions":"在常规工作中坚持思想实验，质疑经典时空观。",
     "breakthrough":"提出狭义与广义相对论，改变人类对宇宙认知。",
     "key_lesson":"Imagination is more important than knowledge; 保持好奇，敢于质疑权威。"},
    {"id":"tesla","name":"Nikola Tesla","name_cn":"特斯拉","era":"1856-1943","period":"19世纪-20世纪","type":"发明家",
     "vector":{"openness":0.9,"conscientiousness":0.8,"extraversion":0.1,"agreeableness":0.3,"neuroticism":0.6,"leadership":0.4,"risk_taking":0.8,"rationality":0.85,"discipline":0.7,"empathy":0.2,"ambition":0.9,"resilience":0.7},
     "early_career":"自学成才，在交流电系统领域开创性研究。",
     "early_actions":"与爱迪生展开电流大战，建立特斯拉线圈。",
     "breakthrough":"发明交流电系统，奠定现代电力工业基础。",
     "key_lesson":"Focus on innovation, not competition; 远见比竞争更重要。"},
    {"id":"galileo","name":"Galileo Galilei","name_cn":"伽利略","era":"1564-1642","period":"文艺复兴","type":"科学家",
     "vector":{"openness":0.95,"conscientiousness":0.8,"extraversion":0.3,"agreeableness":0.2,"neuroticism":0.4,"leadership":0.4,"risk_taking":0.9,"rationality":0.9,"discipline":0.8,"empathy":0.3,"ambition":0.6,"resilience":0.7},
     "early_career":"医学世家出身，自学数学与天文学。",
     "early_actions":"改进望远镜，观测天体运动。",
     "breakthrough":"支持日心说，奠定现代观测天文学基础。",
     "key_lesson":"Evidence over authority; 证据优于权威。"},
    {"id":"mozart","name":"Wolfgang Amadeus Mozart","name_cn":"莫扎特","era":"1756-1791","period":"古典时期","type":"艺术家",
     "vector":{"openness":0.98,"conscientiousness":0.6,"extraversion":0.7,"agreeableness":0.5,"neuroticism":0.7,"leadership":0.3,"risk_taking":0.6,"rationality":0.6,"discipline":0.5,"empathy":0.8,"ambition":0.8,"resilience":0.5},
     "early_career":"神童时期巡回演出，展现惊人音乐天赋。",
     "early_actions":"创作大量交响乐、歌剧与室内乐。",
     "breakthrough":"创作《魔笛》《费加罗的婚礼》等经典歌剧。",
     "key_lesson":"Creativity thrives on freedom; 创造力需要自由。"},
    {"id":"shakespeare","name":"William Shakespeare","name_cn":"莎士比亚","era":"1564-1616","period":"文艺复兴","type":"作家",
     "vector":{"openness":0.9,"conscientiousness":0.7,"extraversion":0.6,"agreeableness":0.5,"neuroticism":0.5,"leadership":0.4,"risk_taking":0.5,"rationality":0.7,"discipline":0.7,"empathy":0.9,"ambition":0.7,"resilience":0.8},
     "early_career":" Stratford小镇出身，伦敦剧院演员兼编剧。",
     "early_actions":"创作大量戏剧与十四行诗。",
     "breakthrough":"写出《哈姆雷特》《麦克白》等经典剧作。",
     "key_lesson":"All the world's a stage; 洞察人性是永恒主题。"},
    {"id":"curie","name":"Marie Curie","name_cn":"居里夫人","era":"1867-1934","period":"19-20世纪","type":"科学家",
     "vector":{"openness":0.85,"conscientiousness":0.95,"extraversion":0.2,"agreeableness":0.6,"neuroticism":0.3,"leadership":0.6,"risk_taking":0.7,"rationality":0.9,"discipline":0.95,"empathy":0.5,"ambition":0.9,"resilience":0.95},
     "early_career":"波兰出身，巴黎大学艰苦求学。",
     "early_actions":"深入研究放射性物质。",
     "breakthrough":"发现钋和镭，两次获得诺贝尔奖。",
     "key_lesson":"Nothing in life is to be feared; 专注与坚韧可以改变世界。"},
    {"id":"lincoln","name":"Abraham Lincoln","name_cn":"林肯","era":"1809-1865","period":"19世纪","type":"政治家",
     "vector":{"openness":0.6,"conscientiousness":0.9,"extraversion":0.4,"agreeableness":0.7,"neuroticism":0.6,"leadership":0.95,"risk_taking":0.6,"rationality":0.85,"discipline":0.8,"empathy":0.8,"ambition":0.7,"resilience":0.95},
     "early_career":"贫苦出身，自学法律成为律师。",
     "early_actions":"领导废奴运动，应对南北战争。",
     "breakthrough":"颁布《解放宣言》，维护美国统一。",
     "key_lesson":"A house divided against itself cannot stand; 坚持信念，勇于担当。"},
    {"id":"steve_jobs","name":"Steve Jobs","name_cn":"史蒂夫·乔布斯","era":"1955-2011","period":"现代","type":"企业家",
     "vector":{"openness":0.85,"conscientiousness":0.7,"extraversion":0.6,"agreeableness":0.3,"neuroticism":0.7,"leadership":0.9,"risk_taking":0.9,"rationality":0.7,"discipline":0.7,"empathy":0.4,"ambition":0.95,"resilience":0.8},
     "early_career":"辍学后自学书法，创立苹果公司。",
     "early_actions":"推出Macintosh，后创立NeXT与Pixar。",
     "breakthrough":"重新定义个人电脑、音乐与手机产业。",
     "key_lesson":"Stay hungry, stay foolish; 创新改变世界。"},
    {"id":"elon_musk","name":"Elon Musk","name_cn":"埃隆·马斯克","era":"1971-","period":"现代","type":"企业家",
     "vector":{"openness":0.9,"conscientiousness":0.6,"extraversion":0.7,"agreeableness":0.3,"neuroticism":0.6,"leadership":0.95,"risk_taking":0.95,"rationality":0.75,"discipline":0.6,"empathy":0.3,"ambition":1.0,"resilience":0.85},
     "early_career":"南非出身，移民美国创办Zip2与PayPal。",
     "early_actions":"创立SpaceX与Tesla，收购Twitter。",
     "breakthrough":"推动电动汽车与太空探索商业化。",
     "key_lesson":"First principles thinking; 从第一性原理出发。"},
    {"id":"mark_zuckerberg","name":"Mark Zuckerberg","name_cn":"马克·扎克伯格","era":"1984-","period":"现代","type":"企业家",
     "vector":{"openness":0.7,"conscientiousness":0.8,"extraversion":0.4,"agreeableness":0.4,"neuroticism":0.3,"leadership":0.85,"risk_taking":0.7,"rationality":0.7,"discipline":0.8,"empathy":0.4,"ambition":0.9,"resilience":0.7},
     "early_career":"哈佛学生，宿舍创建Facebook。",
     "early_actions":"将Facebook发展为全球社交平台。",
     "breakthrough":"开创社交网络时代，连接数十亿人。",
     "key_lesson":"Move fast and break things; 快速迭代，拥抱变化。"},
    {"id":"bill_gates","name":"Bill Gates","name_cn":"比尔·盖茨","era":"1955-","period":"现代","type":"企业家",
     "vector":{"openness":0.75,"conscientiousness":0.95,"extraversion":0.5,"agreeableness":0.6,"neuroticism":0.2,"leadership":0.8,"risk_taking":0.6,"rationality":0.95,"discipline":0.95,"empathy":0.6,"ambition":0.85,"resilience":0.8},
     "early_career":"哈佛辍学，与保罗·艾伦创立微软。",
     "early_actions":"开创个人电脑软件时代。",
     "breakthrough":"Windows操作系统改变世界，后投身慈善。",
     "key_lesson":"Success is a lousy teacher; 成功不能让人自满。"},
    {"id":"warren_buffett","name":"Warren Buffett","name_cn":"沃伦·巴菲特","era":"1930-","period":"现代","type":"企业家",
     "vector":{"openness":0.5,"conscientiousness":0.9,"extraversion":0.3,"agreeableness":0.7,"neuroticism":0.1,"leadership":0.7,"risk_taking":0.3,"rationality":0.9,"discipline":0.95,"empathy":0.6,"ambition":0.6,"resilience":0.85},
     "early_career":"价值投资理念奠基者，伯克希尔·哈撒韦CEO。",
     "early_actions":"长期价值投资策略，收购优质企业。",
     "breakthrough":"成为世界最成功投资者之一，践行价值投资。",
     "key_lesson":"Price is what you pay; value is what you get; 价格与价值不同。"},
    {"id":"edison","name":"Thomas Edison","name_cn":"爱迪生","era":"1847-1931","period":"19世纪","type":"发明家",
     "vector":{"openness":0.7,"conscientiousness":0.85,"extraversion":0.5,"agreeableness":0.4,"neuroticism":0.5,"leadership":0.6,"risk_taking":0.6,"rationality":0.8,"discipline":0.9,"empathy":0.4,"ambition":0.8,"resilience":0.9},
     "early_career":"自学成才，童年被老师认为「太笨」。",
     "early_actions":"建立门洛帕克实验室，系统创新。",
     "breakthrough":"发明电灯、留声机等改变世界的产品。",
     "key_lesson":"Genius is one percent inspiration; 天才是百分之一的灵感。"},
    {"id":"freud","name":"Sigmund Freud","name_cn":"弗洛伊德","era":"1856-1939","period":"19-20世纪","type":"心理学家",
     "vector":{"openness":0.85,"conscientiousness":0.7,"extraversion":0.3,"agreeableness":0.3,"neuroticism":0.7,"leadership":0.5,"risk_taking":0.5,"rationality":0.65,"discipline":0.7,"empathy":0.5,"ambition":0.7,"resilience":0.6},
     "early_career":"维也纳医生，研究神经学。",
     "early_actions":"创立精神分析学派。",
     "breakthrough":"提出潜意识理论，开创心理分析。",
     "key_lesson":"The unconscious is the true psychic reality; 潜意识决定行为。"},
    {"id":"darwin","name":"Charles Darwin","name_cn":"达尔文","era":"1809-1882","period":"19世纪","type":"科学家",
     "vector":{"openness":0.9,"conscientiousness":0.85,"extraversion":0.2,"agreeableness":0.5,"neuroticism":0.5,"leadership":0.3,"risk_taking":0.6,"rationality":0.9,"discipline":0.85,"empathy":0.6,"ambition":0.6,"resilience":0.7},
     "early_career":"贝格尔号航行，环球考察。",
     "early_actions":"收集物种样本，研究自然选择。",
     "breakthrough":"提出进化论，发表《物种起源》。",
     "key_lesson":"It is not the strongest that survive; 适者生存。"},
    {"id":"pasteur","name":"Louis Pasteur","name_cn":"巴斯德","era":"1822-1895","period":"19世纪","type":"科学家",
     "vector":{"openness":0.8,"conscientiousness":0.9,"extraversion":0.4,"agreeableness":0.6,"neuroticism":0.3,"leadership":0.6,"risk_taking":0.5,"rationality":0.9,"discipline":0.9,"empathy":0.5,"ambition":0.7,"resilience":0.8},
     "early_career":"化学家出身，研究发酵与微生物。",
     "early_actions":"发明巴氏消毒法，研发狂犬病疫苗。",
     "breakthrough":"奠定微生物学基础，拯救无数生命。",
     "key_lesson":"Chance favors the prepared mind; 机遇偏爱有准备的头脑。"},
    {"id":"ada_lovelace","name":"Ada Lovelace","name_cn":"阿达·洛夫莱斯","era":"1815-1852","period":"19世纪","type":"科学家",
     "vector":{"openness":0.95,"conscientiousness":0.8,"extraversion":0.4,"agreeableness":0.5,"neuroticism":0.4,"leadership":0.4,"risk_taking":0.6,"rationality":0.85,"discipline":0.8,"empathy":0.5,"ambition":0.7,"resilience":0.6},
     "early_career":"数学家拜伦之女，自学数学与机械。",
     "early_actions":"为巴贝奇分析机编写算法。",
     "breakthrough":"写出世界上第一个计算机程序，预见计算机的未来。",
     "key_lesson":"The Analytical Engine weaves algebraic patterns; 诗意与逻辑可以结合。"},
    {"id":"florence_nightingale","name":"Florence Nightingale","name_cn":"南丁格尔","era":"1820-1910","period":"19世纪","type":"医生",
     "vector":{"openness":0.6,"conscientiousness":0.95,"extraversion":0.5,"agreeableness":0.8,"neuroticism":0.4,"leadership":0.8,"risk_taking":0.6,"rationality":0.75,"discipline":0.95,"empathy":0.95,"ambition":0.7,"resilience":0.9},
     "early_career":"贵族出身，违背家庭意愿成为护士。",
     "early_actions":"克里米亚战争护理伤员。",
     "breakthrough":"建立现代护理学，创立南丁格尔统计方法。",
     "key_lesson":"The art of nursing is... the application of science; 科学服务于人道。"},
    {"id":"helen_keller","name":"Helen Keller","name_cn":"海伦·凯勒","era":"1880-1968","period":"20世纪","type":"作家",
     "vector":{"openness":0.8,"conscientiousness":0.85,"extraversion":0.6,"agreeableness":0.9,"neuroticism":0.3,"leadership":0.7,"risk_taking":0.5,"rationality":0.7,"discipline":0.9,"empathy":1.0,"ambition":0.8,"resilience":1.0},
     "early_career":"幼年失明失聪，在莎莉文老师帮助下学习。",
     "early_actions":"克服障碍，考入哈佛大学。",
     "breakthrough":"成为著名作家与社会活动家，推动残障权益。",
     "key_lesson":"Optimism is the faith that leads to achievement; 乐观是成就的信仰。"},
]

def random_fig():
    dims = ["openness","conscientiousness","extraversion","agreeableness","neuroticism","leadership","risk_taking","rationality","discipline","empathy","ambition","resilience"]
    v = {d: round(random.uniform(0.2,0.95),2) for d in dims}
    return {
        "id": f"figure_{random.randint(1,9999)}",
        "name": f"Historical Figure {random.randint(1,100)}",
        "name_cn": f"历史人物{random.randint(1,100)}",
        "era": f"{random.randint(1500,2000)}-{random.randint(1550,2020)}",
        "period": f"{random.choice(['古代','中世纪','近代','现代'])}",
        "type": random.choice(["科学家","艺术家","政治家","企业家","发明家","心理学家","作家"]),
        "vector": v,
        "early_career": "早期经历与教育积累。",
        "early_actions": "关键行动与决策。",
        "breakthrough": "核心成就与贡献。",
        "key_lesson": "人生教训与启示。"
    }

def main():
    Path("src/data").mkdir(parents=True, exist_ok=True)
    figures = REAL + [random_fig() for _ in range(80)]
    with open("src/data/figures.json","w",encoding="utf-8") as f:
        json.dump({"figures": figures}, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(figures)} figures.")

if __name__ == "__main__":
    main()
